### ISSUE TITLE
Android app crashes after updated plugin to 7.4.0 

### ISSUE THREAD

**Issue by janossuta** [EddyVerbruggen/nativescript-plugin-firebase#1029]
Hi,

I have updated my app to the nativescript 5.0 and I got some java error after the firebase plugin initialized but the application still running.

```
11-14 21:23:28.725  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
11-14 21:23:28.725  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1116)
11-14 21:23:28.725  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:996)
11-14 21:23:28.725  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:983)
11-14 21:23:28.725  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:967)
11-14 21:23:28.725  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:959)
11-14 21:23:28.726  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
11-14 21:23:28.726  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1116)
11-14 21:23:28.726  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:996)
11-14 21:23:28.726  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:983)
11-14 21:23:28.726  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:967)
11-14 21:23:28.726  7007  7007 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:959)
11-14 21:23:39.208  7007  7007 W ExifInterface:         at com.tns.Runtime.callJSMethodNative(Native Method)
11-14 21:23:39.208  7007  7007 W ExifInterface:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
11-14 21:23:39.208  7007  7007 W ExifInterface:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
11-14 21:23:39.208  7007  7007 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:983)
11-14 21:23:39.208  7007  7007 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:967)
11-14 21:23:39.208  7007  7007 W ExifInterface:         at com.tns.Runtime.callJSMethod(Runtime.java:959)
```

So I checked if there is a newer version of your plugin and I saw that you made one (7.4.0) so I updated my app but after that it crashes without any error message (both on emulator and phone)

I tried both 7.4.0 and 7.4.1

This happens on Android, I haven't tested it on IOS yet

here is my [package.json](https://gist.github.com/janossuta/10a16162e445d59a8ea96114daba1846) 

I think this ticket is related to mine: [#1026](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/1026)

I tried to run your demo app, but I got some error message:
```
g:\temp\nativescript-plugin-firebase\src>npm run demo.android

> nativescript-plugin-firebase@7.4.1 demo.android g:\temp\nativescript-plugin-firebase\src
> npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android


> nativescript-plugin-firebase@7.4.1 preparedemo g:\temp\nativescript-plugin-firebase\src
> npm run tsc && npm run package && cd ../demo && tns plugin add ../publish/package/*.tgz && tns install


> nativescript-plugin-firebase@7.4.1 tsc g:\temp\nativescript-plugin-firebase\src
> tsc -skipLibCheck


> nativescript-plugin-firebase@7.4.1 package g:\temp\nativescript-plugin-firebase\src
> cd ../publish && ./pack.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-plugin-firebase@7.4.1 package: `cd ../publish && ./pack.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-plugin-firebase@7.4.1 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2018-11-14T20_53_20_566Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-plugin-firebase@7.4.1 preparedemo: `npm run tsc && npm run package && cd ../demo && tns plugin add ../publish/package/*.tgz && tns install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-plugin-firebase@7.4.1 preparedemo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2018-11-14T20_53_20_585Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-plugin-firebase@7.4.1 demo.android: `npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-plugin-firebase@7.4.1 demo.android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2018-11-14T20_53_20_605Z-debug.log
```
and this is from the log file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'demo.android' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'predemo.android', 'demo.android', 'postdemo.android' ]
5 info lifecycle nativescript-plugin-firebase@7.4.1~predemo.android: nativescript-plugin-firebase@7.4.1
6 info lifecycle nativescript-plugin-firebase@7.4.1~demo.android: nativescript-plugin-firebase@7.4.1
7 verbose lifecycle nativescript-plugin-firebase@7.4.1~demo.android: unsafe-perm in lifecycle true
9 verbose lifecycle nativescript-plugin-firebase@7.4.1~demo.android: CWD: g:\temp\nativescript-plugin-firebase\src
10 silly lifecycle nativescript-plugin-firebase@7.4.1~demo.android: Args: [ '/d /s /c',
10 silly lifecycle   'npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android' ]
11 silly lifecycle nativescript-plugin-firebase@7.4.1~demo.android: Returned: code: 1  signal: null
12 info lifecycle nativescript-plugin-firebase@7.4.1~demo.android: Failed to exec demo.android script
13 verbose stack Error: nativescript-plugin-firebase@7.4.1 demo.android: `npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid nativescript-plugin-firebase@7.4.1
15 verbose cwd g:\temp\nativescript-plugin-firebase\src
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "demo.android"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error nativescript-plugin-firebase@7.4.1 demo.android: `npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android`
22 error Exit status 1
23 error Failed at the nativescript-plugin-firebase@7.4.1 demo.android script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by EddyVerbruggen** [comment]
Do you have Crashlytics enabled? I’m working on a fix for that currently. If not please share a repo and I might take a look.

**Comment by janossuta** [comment]
Hi @EddyVerbruggen, 
No I haven't enabled Crashlytics. 
I'm going to prepare a repo and then share that with you but in the meantime I tried 7.4.2 but the issue remained. 

Any idea why I can't make your demo run?

**Comment by EddyVerbruggen** [comment]
Without telling me what you tried I can’t.

**Comment by janossuta** [comment]
I cloned your repo then follow the steps

- cd src.
- npm i (just answer 'n' to any prompts as they are ignored anyway).
- npm run demo.ios or npm run demo.android (answer 'n' again if prompted).

and I got the previously described error message

```
g:\temp\nativescript-plugin-firebase\src>npm run demo.android

> nativescript-plugin-firebase@7.4.1 demo.android g:\temp\nativescript-plugin-firebase\src
> npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android


> nativescript-plugin-firebase@7.4.1 preparedemo g:\temp\nativescript-plugin-firebase\src
> npm run tsc && npm run package && cd ../demo && tns plugin add ../publish/package/*.tgz && tns install


> nativescript-plugin-firebase@7.4.1 tsc g:\temp\nativescript-plugin-firebase\src
> tsc -skipLibCheck


> nativescript-plugin-firebase@7.4.1 package g:\temp\nativescript-plugin-firebase\src
> cd ../publish && ./pack.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-plugin-firebase@7.4.1 package: `cd ../publish && ./pack.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-plugin-firebase@7.4.1 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2018-11-14T20_53_20_566Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-plugin-firebase@7.4.1 preparedemo: `npm run tsc && npm run package && cd ../demo && tns plugin add ../publish/package/*.tgz && tns install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-plugin-firebase@7.4.1 preparedemo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2018-11-14T20_53_20_585Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-plugin-firebase@7.4.1 demo.android: `npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-plugin-firebase@7.4.1 demo.android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2018-11-14T20_53_20_605Z-debug.log
```
and this is from the log file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'demo.android' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'predemo.android', 'demo.android', 'postdemo.android' ]
5 info lifecycle nativescript-plugin-firebase@7.4.1~predemo.android: nativescript-plugin-firebase@7.4.1
6 info lifecycle nativescript-plugin-firebase@7.4.1~demo.android: nativescript-plugin-firebase@7.4.1
7 verbose lifecycle nativescript-plugin-firebase@7.4.1~demo.android: unsafe-perm in lifecycle true
9 verbose lifecycle nativescript-plugin-firebase@7.4.1~demo.android: CWD: g:\temp\nativescript-plugin-firebase\src
10 silly lifecycle nativescript-plugin-firebase@7.4.1~demo.android: Args: [ '/d /s /c',
10 silly lifecycle   'npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android' ]
11 silly lifecycle nativescript-plugin-firebase@7.4.1~demo.android: Returned: code: 1  signal: null
12 info lifecycle nativescript-plugin-firebase@7.4.1~demo.android: Failed to exec demo.android script
13 verbose stack Error: nativescript-plugin-firebase@7.4.1 demo.android: `npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid nativescript-plugin-firebase@7.4.1
15 verbose cwd g:\temp\nativescript-plugin-firebase\src
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "demo.android"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error nativescript-plugin-firebase@7.4.1 demo.android: `npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android`
22 error Exit status 1
23 error Failed at the nativescript-plugin-firebase@7.4.1 demo.android script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
firebase.nativescript.json
```
{
  "using_ios": true,
  "using_android": true,
  "realtimedb": true,
  "firestore": false,
  "remote_config": false,
  "performance_monitoring": false,
  "messaging": false,
  "crash_reporting": false,
  "crashlytics": false,
  "storage": false,
  "facebook_auth": false,
  "google_auth": false,
  "admob": false,
  "invites": false,
  "dynamic_links": false,
  "ml_kit": false,
  "ml_kit_text_recognition": false,
  "ml_kit_barcode_scanning": false,
  "ml_kit_face_detection": false,
  "ml_kit_image_labeling": false,
  "ml_kit_custom_model": false
}
```

**Comment by EddyVerbruggen** [comment]
Yeah on windows `./pack.sh` won't work, but nevermind running the demo app. Can you share that repo?

**Comment by janossuta** [comment]
hi @EddyVerbruggen,

Here is my [repo](https://github.com/janossuta/demoApp)

**Comment by EddyVerbruggen** [comment]
See the note at the top: 
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ADMOB.md#enabling-admob

**Comment by janossuta** [comment]
Thanks I deactivated admob and the crash is disappeared but after firebase init I still get this java errors
and this was the main reason for updating the plugin 

```
1-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
11-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1116)
11-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:996)
11-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:983)
11-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:967)
11-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:959)
11-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
11-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1116)
11-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:996)
11-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:983)
11-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:967)
11-18 20:54:52.136 15030 15030 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:959)
```

**Comment by EddyVerbruggen** [comment]
Is there an actual issue or it’s just that those log messages are annoying?

**Comment by janossuta** [comment]
just the log messages, I don't know what are those

**Comment by EddyVerbruggen** [comment]
Me neither, but they don’t worry me enough to investigate further.
