### ISSUE TITLE
Nativescript Angular Demo not working

### ISSUE THREAD

**Issue by Jxckaroo** [EddyVerbruggen/nativescript-plugin-firebase#1116]
When i try to run the demo android app on a windows machine with the android studio emulator, i seem to get the following error after running npm run demo.android:

> nativescript-plugin-firebase@7.7.0 package C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src
> cd ../publish && ./pack.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-plugin-firebase@7.7.0 package: `cd ../publish && ./pack.sh`
npm ERR! Exit status 1

Any ideas?

**Comment by NickIliev** [comment]
@Jxckaroo I've updated all dependencies to latest and the demo is working as expected on my side.

Here is the updated package.json
```JSON
  "dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/http": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "nativescript-angular": "^7.1.2",
    "nativescript-camera": "~4.1.1",
    "nativescript-imagepicker": "~6.0.6",
    "nativescript-plugin-firebase": "7.7.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.3.3",
    "tns-core-modules": "~5.1.2",
    "zone.js": "~0.8.28"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~7.1.0",
    "@ngtools/webpack": "~7.1.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.7.9",
    "nativescript-dev-webpack": "^0.19.0",
    "typescript": "~3.1.1"
  }
```

**Comment by Jxckaroo** [comment]
@NickIliev Are you on a windows machine? Because i have updated the dependencies to match yours and here is my output when running npm run demo-ng.android

>PS C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src> npm run demo.android

> nativescript-plugin-firebase@7.7.0 demo.android C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src
> npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android


> nativescript-plugin-firebase@7.7.0 preparedemo C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src
> npm run tsc && npm run package && cd ../demo && tns plugin add ../publish/package/*.tgz && tns install


> nativescript-plugin-firebase@7.7.0 tsc C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src
> tsc -skipLibCheck


> nativescript-plugin-firebase@7.7.0 package C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src
> cd ../publish && ./pack.sh

>'.' is not recognized as an internal or external command, operable program or batch file.
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! nativescript-plugin-firebase@7.7.0 package: `cd ../publish && ./pack.sh`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the nativescript-plugin-firebase@7.7.0 package script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\Jack\AppData\Roaming\npm-cache\_logs\2019-01-22T18_34_12_783Z-debug.log
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! nativescript-plugin-firebase@7.7.0 preparedemo: `npm run tsc && npm run package && cd ../demo && tns plugin add ../publish/package/*.tgz && tns install`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the nativescript-plugin-firebase@7.7.0 preparedemo script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\Jack\AppData\Roaming\npm-cache\_logs\2019-01-22T18_34_12_796Z-debug.log
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! nativescript-plugin-firebase@7.7.0 demo.android: `npm run preparedemo && cd ../demo && rimraf platforms/android && tns run android`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the nativescript-plugin-firebase@7.7.0 demo.android script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\Jack\AppData\Roaming\npm-cache\_logs\2019-01-22T18_34_12_811Z-debug.log
>PS C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src>

Below is also the NPM log output:

>0 info it worked if it ends with ok
>1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
>1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
>1 verbose cli   'run',
>1 verbose cli   'pack' ]
>2 info using npm@5.6.0
>3 info using node@v8.11.4
>4 verbose run-script [ 'prepack', 'pack', 'postpack' ]
>5 info lifecycle nativescript-plugin-firebase@7.7.0~prepack: nativescript-plugin-firebase@7.7.0
>6 info lifecycle nativescript-plugin-firebase@7.7.0~pack: nativescript-plugin-firebase@7.7.0
>7 verbose lifecycle nativescript-plugin-firebase@7.7.0~pack: unsafe-perm in lifecycle true
>8 verbose lifecycle nativescript-plugin-firebase@7.7.0~pack: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Users\Jack\Desktop\Pace\ffmpeg\bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Jack\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Boxcryptor\bin\;E:\Development\php;C:\ProgramData\ComposerSetup\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_144\bin;C:\Android\android-sdk\tools;C:\Android\android-sdk\platform-tools;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\Jack\AppData\Roaming\npm;C:\Program Files\nodejs;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\Jack\AppData\Roaming\Composer\vendor\bin;C:\Users\Jack\AppData\Local\Programs\Fiddler;C:\Program Files\Git\bin;C:\Program Files\Git;C:\Users\Jack\AppData\Local\.meteor
>9 verbose lifecycle nativescript-plugin-firebase@7.7.0~pack: CWD: C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src
>10 silly lifecycle nativescript-plugin-firebase@7.7.0~pack: Args: [ '/d /s /c', './pack.sh' ]
>11 silly lifecycle nativescript-plugin-firebase@7.7.0~pack: Returned: code: 1  signal: null
>12 info lifecycle nativescript-plugin-firebase@7.7.0~pack: Failed to exec pack script
>13 verbose stack Error: nativescript-plugin-firebase@7.7.0 pack: `./pack.sh`
>13 verbose stack Exit status 1
>13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
>13 verbose stack     at emitTwo (events.js:126:13)
>13 verbose stack     at EventEmitter.emit (events.js:214:7)
>13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
>13 verbose stack     at emitTwo (events.js:126:13)
>13 verbose stack     at ChildProcess.emit (events.js:214:7)
>13 verbose stack     at maybeClose (internal/child_process.js:925:16)
>13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
>14 verbose pkgid nativescript-plugin-firebase@7.7.0
>15 verbose cwd C:\Users\Jack\Desktop\Projects\nativescript-plugin-firebase\src
>16 verbose Windows_NT 10.0.17134
>17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "pack"
>18 verbose node v8.11.4
>19 verbose npm  v5.6.0
>20 error code ELIFECYCLE
>21 error errno 1
>22 error nativescript-plugin-firebase@7.7.0 pack: `./pack.sh`
>22 error Exit status 1
>23 error Failed at the nativescript-plugin-firebase@7.7.0 pack script.
>23 error This is probably not a problem with npm. There is likely additional logging output above.
>24 verbose exit [ 1, true ]

**Comment by NickIliev** [comment]
@Jxckaroo yes I am testing on Windows as well, but instead of the provided npm scripts I've started the demo directly via the CLI
```
cd demo-ng
tns run android --bundle
```

**Comment by Jxckaroo** [comment]
> @Jxckaroo yes I am testing on Windows as well, but instead of the provided npm scripts I've started the demo directly via the CLI
> 
> ```
> cd demo-ng
> tns run android --bundle
> ```

That seemed to get it working thanks. 

Looks like the npm scripts are not optimised for windows?

**Comment by ezpzlmnsqzy1** [comment]
note: i had to run "pack.cmd" manually in "nativescript-plugin-firebase\publish" for `cd demo-ng
tns run android --bundle` to work
