### ISSUE TITLE
Active listener after logout

### ISSUE THREAD

**Issue by andrew19881123** [EddyVerbruggen/nativescript-plugin-firebase#122]
I'm creating an app with nativescript, firebase and angular 2, in a component I have:

```
ngOnInit() {
     firebase.addChildEventListener(this.onChildEvent, "/stories");	
}

onChildEvent = (result) => {
   //do something		
};

logout() {
   firebase.logout()
   .catch((err) => {
        console.log(err);
    });
}
```

When I log out I get an error like the listener is still attached to firebase after logout, if I comment the line of the addChildEventListener the logout works. I also have another listener in place, the onAuthStateChanged, which might be the "Notified 1 auth state listeners" in the logs.

stacktrace:
```
09-01 23:58:17.655 10412 10412 D FirebaseAuth: Notifying listeners about a sign-out event.
09-01 23:58:17.751 10412 10412 D FirebaseApp: Notifying auth state listeners.
09-01 23:58:17.751 10412 10412 D FirebaseApp: Notified 1 auth state listeners.
09-01 23:58:17.752 10412 10412 V JS      : Logged out from firebase
09-01 23:58:18.620 10412 10479 W SyncTree: Listen at /stories failed: DatabaseError: Permission denied
09-01 23:58:18.648 10412 10412 D AndroidRuntime: Shutting down VM
09-01 23:58:18.649 10412 10412 W System.err: com.tns.NativeScriptException: 
09-01 23:58:18.649 10412 10412 W System.err: Calling js method onCancelled failed
09-01 23:58:18.649 10412 10412 W System.err: Error: java.lang.AbstractMethodError: abstract method "void com.google.firebase.database.ChildEventListener.onCancelled(com.google.firebase.database.DatabaseError)"
09-01 23:58:18.649 10412 10412 W System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
09-01 23:58:18.649 10412 10412 W System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:862)
09-01 23:58:18.649 10412 10412 W System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:727)
09-01 23:58:18.649 10412 10412 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:713)
09-01 23:58:18.650 10412 10412 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:694)
09-01 23:58:18.650 10412 10412 W System.err:     com.tns.Runtime.callJSMethod(Runtime.java:684)
09-01 23:58:18.650 10412 10412 W System.err:     com.tns.gen.com.google.firebase.database.ChildEventListener.onCancelled(ChildEventListener.java:38)
09-01 23:58:18.650 10412 10412 W System.err:     com.google.android.gms.internal.zzahe.zza(Unknown Source)
09-01 23:58:18.650 10412 10412 W System.err:     com.google.android.gms.internal.zzajc.zzcta(Unknown Source)
09-01 23:58:18.650 10412 10412 W System.err:     com.google.android.gms.internal.zzajh$1.run(Unknown Source)
09-01 23:58:18.650 10412 10412 W System.err:     android.os.Handler.handleCallback(Handler.java:739)
09-01 23:58:18.650 10412 10412 W System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
09-01 23:58:18.650 10412 10412 W System.err:     android.os.Looper.loop(Looper.java:148)
09-01 23:58:18.650 10412 10412 W System.err:     android.app.ActivityThread.main(ActivityThread.java:5417)
09-01 23:58:18.650 10412 10412 W System.err:     java.lang.reflect.Method.invoke(Native Method)
09-01 23:58:18.650 10412 10412 W System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-01 23:58:18.650 10412 10412 W System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-01 23:58:18.650 10412 10412 W System.err: File: "<unknown>, line: 0, column: -1
09-01 23:58:18.650 10412 10412 W System.err: StackTrace: 
09-01 23:58:18.650 10412 10412 W System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
09-01 23:58:18.650 10412 10412 W System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:862)
09-01 23:58:18.650 10412 10412 W System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:727)
09-01 23:58:18.650 10412 10412 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:713)
09-01 23:58:18.650 10412 10412 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:694)
09-01 23:58:18.650 10412 10412 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:684)
09-01 23:58:18.650 10412 10412 W System.err: 	at com.tns.gen.com.google.firebase.database.ChildEventListener.onCancelled(ChildEventListener.java:38)
09-01 23:58:18.650 10412 10412 W System.err: 	at com.google.android.gms.internal.zzahe.zza(Unknown Source)
09-01 23:58:18.650 10412 10412 W System.err: 	at com.google.android.gms.internal.zzajc.zzcta(Unknown Source)
09-01 23:58:18.650 10412 10412 W System.err: 	at com.google.android.gms.internal.zzajh$1.run(Unknown Source)
09-01 23:58:18.650 10412 10412 W System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
09-01 23:58:18.650 10412 10412 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-01 23:58:18.650 10412 10412 W System.err: 	at android.os.Looper.loop(Looper.java:148)
09-01 23:58:18.650 10412 10412 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
09-01 23:58:18.650 10412 10412 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-01 23:58:18.650 10412 10412 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-01 23:58:18.650 10412 10412 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-01 23:58:18.650 10412 10412 W System.err: Caused by: java.lang.AbstractMethodError: abstract method "void com.google.firebase.database.ChildEventListener.onCancelled(com.google.firebase.database.DatabaseError)"
09-01 23:58:18.650 10412 10412 W System.err: 	... 17 more
09-01 23:58:18.656   777  1796 I ActivityManager: START u0 {flg=0x14008000 cmp=org.nativescript.firebasetest2/com.tns.ErrorReportActivity (has extras)} from uid 10303 on display 0
09-01 23:58:18.686 10412 10412 I Process : Sending signal. PID: 10412 SIG: 9
09-01 23:58:18.731   777   874 W InputDispatcher: channel 'a0802cd org.nativescript.firebasetest2/com.tns.NativeScriptActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-01 23:58:18.731   777   874 E InputDispatcher: channel 'a0802cd org.nativescript.firebasetest2/com.tns.NativeScriptActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-01 23:58:18.732   777  1797 D GraphicsStats: Buffer count: 6
09-01 23:58:18.732   777  1796 I WindowState: WIN DEATH: Window{a0802cd u0 org.nativescript.firebasetest2/com.tns.NativeScriptActivity}
09-01 23:58:18.732   777  1796 W InputDispatcher: Attempted to unregister already unregistered input channel 'a0802cd org.nativescript.firebasetest2/com.tns.NativeScriptActivity (server)'
09-01 23:58:18.761   777  4784 I ActivityManager: Process org.nativescript.firebasetest2 (pid 10412) has died
09-01 23:58:18.781   777  4784 I ActivityManager: Start proc 10707:org.nativescript.firebasetest2/u0a303 for activity org.nativescript.firebasetest2/com.tns.ErrorReportActivity
09-01 23:58:18.781 10707 10707 I art     : Late-enabling -Xcheck:jni
09-01 23:58:18.875 10707 10720 W DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
09-01 23:58:18.903 10707 10720 W DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
09-01 23:58:18.939 10707 10720 D ChimeraCfgMgr: Reading stored module config
09-01 23:58:18.957 10707 10707 I DynamiteModule: Considering local module com.google.android.gms.flags:0 and remote module com.google.android.gms.flags:1
09-01 23:58:18.957 10707 10707 I DynamiteModule: Selected remote version of com.google.android.gms.flags, version >= 1
09-01 23:58:18.970 10707 10707 W DynamiteModule: Local module descriptor class for com.google.android.gms.crash not found.
09-01 23:58:18.970 10707 10707 I DynamiteModule: Considering local module com.google.android.gms.crash:0 and remote module com.google.android.gms.crash:3
09-01 23:58:18.970 10707 10707 I DynamiteModule: Selected remote version of com.google.android.gms.crash, version >= 3
09-01 23:58:18.978 10707 10707 W System  : ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000008/n/armeabi-v7a
09-01 23:58:18.978 10707 10707 W System  : ClassLoader referenced unknown path: /data/user/0/com.google.android.gms/app_chimera/m/00000008/n/armeabi
09-01 23:58:18.979 10707 10707 D ChimeraFileApk: Primary ABI of requesting process is armeabi-v7a
09-01 23:58:18.980 10707 10707 D ChimeraFileApk: Classloading successful. Optimized code found.
09-01 23:58:18.984 10707 10707 I FirebaseCrashApiImpl: FirebaseCrashApiImpl created by ClassLoader com.google.android.chimera.container.internal.DelegateLastPathClassLoader[DexPathList[[zip file "/data/data/com.google.android.gms/app_chimera/m/00000008/DynamiteModulesC_GmsCore_prodmnc_xxhdpi_release.apk"],nativeLibraryDirectories=[/data/user/0/com.google.android.gms/app_chimera/m/00000008/n/armeabi-v7a, /data/user/0/com.google.android.gms/app_chimera/m/00000008/n/armeabi, /vendor/lib, /system/lib]]]
09-01 23:58:18.990 10707 10707 I DynamiteModule: Considering local module com.google.android.gms.flags:0 and remote module com.google.android.gms.flags:1
09-01 23:58:18.990 10707 10707 I DynamiteModule: Selected remote version of com.google.android.gms.flags, version >= 1
09-01 23:58:19.014 10707 10707 D FirebaseCrashApiImpl: FirebaseCrash reporting API initialized
09-01 23:58:19.015 10707 10707 I FirebaseCrash: FirebaseCrash reporting initialized com.google.firebase.crash.internal.zzg@1d6dea0
09-01 23:58:19.023 10707 10707 I FA      : App measurement is starting up, version: 9452
09-01 23:58:19.023 10707 10707 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
09-01 23:58:19.048 10707 10707 I FirebaseInitProvider: FirebaseApp initialization successful
09-01 23:58:19.090 10707 10707 I TNS.Native: NativeScript Runtime Version 2.2.0, commit 14f63dd23a93cb0d1af9623d72ccf166e722e35a
09-01 23:58:19.090 10707 10707 D TNS.Native: JNI_ONLoad
09-01 23:58:19.090 10707 10707 D TNS.Native: JNI_ONLoad END
09-01 23:58:19.141  3971  3971 W Binder_5: type=1400 audit(0.0:524556): avc: denied { ioctl } for path="socket:[17221360]" dev="sockfs" ino=17221360 ioctlcmd=7704 scontext=u:r:surfaceflinger:s0 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
09-01 23:58:19.141  3971  3971 W Binder_5: type=1400 audit(0.0:524557): avc: denied { ioctl } for path="socket:[17221360]" dev="sockfs" ino=17221360 ioctlcmd=7704 scontext=u:r:surfaceflinger:s0 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
09-01 23:58:19.154 10707 10737 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
09-01 23:58:19.141  3971  3971 W Binder_5: type=1400 audit(0.0:524558): avc: denied { ioctl } for path="socket:[17221640]" dev="sockfs" ino=17221640 ioctlcmd=7704 scontext=u:r:surfaceflinger:s0 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
09-01 23:58:19.141  3971  3971 W Binder_5: type=1400 audit(0.0:524559): avc: denied { ioctl } for path="socket:[17221640]" dev="sockfs" ino=17221640 ioctlcmd=7704 scontext=u:r:surfaceflinger:s0 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
09-01 23:58:19.231   946   946 W Binder_3: type=1400 audit(0.0:524560): avc: denied { ioctl } for path="socket:[17218822]" dev="sockfs" ino=17218822 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
09-01 23:58:19.231   946   946 W Binder_3: type=1400 audit(0.0:524561): avc: denied { ioctl } for path="socket:[17218822]" dev="sockfs" ino=17218822 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
09-01 23:58:19.316 10707 10737 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
09-01 23:58:19.373 10707 10737 I OpenGLRenderer: Initialized EGL, version 1.4
09-01 23:58:19.456   777   796 I ActivityManager: Displayed org.nativescript.firebasetest2/com.tns.ErrorReportActivity: +686ms
09-01 23:58:19.451   789   789 W Binder_2: type=1400 audit(0.0:524562): avc: denied { ioctl } for path="socket:[17221366]" dev="sockfs" ino=17221366 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
09-01 23:58:19.468   777   789 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 10412 uid 10303
09-01 23:58:19.451   789   789 W Binder_2: type=1400 audit(0.0:524563): avc: denied { ioctl } for path="socket:[17221366]" dev="sockfs" ino=17221366 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
09-01 23:58:19.451  1454  1454 W Binder_5: type=1400 audit(0.0:524564): avc: denied { ioctl } for path="socket:[17221365]" dev="sockfs" ino=17221365 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
09-01 23:58:19.451  1454  1454 W Binder_5: type=1400 audit(0.0:524565): avc: denied { ioctl } for path="socket:[17221365]" dev="sockfs" ino=17221365 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
```

**Comment by EddyVerbruggen** [comment]
Hmm, interesting one. The plugin started out without authentication so this was never an issue, but if you require someone to be authenticated to listen on certain paths then I can imagine this happens so let's fix this!

Would it help if you could remove the eventlisteners yourself, or do you feel the plugin should do it for you when logging out? The problem with the latter is that some listeners may be attached to paths with anonymous access which would also be removed..

**Comment by andrew19881123** [comment]
I agree with you, the best approach is to implement a remove function to selectively remove the listeners. this would come in handy also if you want to change the listening path.
