### ISSUE TITLE
ETIMEDOUT: Cannot perform cloud build for Android using Sidekick

### ISSUE THREAD

**Issue by Izrab** [EddyVerbruggen/nativescript-plugin-firebase#1243]
After installing Firebase Plugin and completing the installing steps, I clicked run on device to build my app on cloud, I get the following error message:

[19-04-26 07:36:36.924] (CLI) (node:9172) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 52.216.129.19:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
    at emitWarning (internal/process/promises.js:81:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
    at process._tickCallback (internal/process/next_tick.js:69:34)
(node:9172) Error: connect ETIMEDOUT 52.216.129.19:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
(node:9172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:95:13)
    at emitWarning (internal/process/promises.js:88:3)
    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
    at process._tickCallback (internal/process/next_tick.js:69:34)
OUTPUT 1

______________________________
I tried removing platforms and cloud folder, also "cloud workplace cleanup", etc. But still did not work.
I have firebase.nativescript.json file in my root folder, I also have google-services.json file in my platforms/android folder, and also I wrote the suggested tags in AndroidManifest.xml

My app is core **plain javascript** project 
I am on Windows 10,
I use Sidekick Version: 1.16.2-v.2019.3.13.12 (latest)
NativeScript CLI version: 5.3.1
CLI extension nativescript-cloud version: 1.17.3
CLI extension nativescript-starter-kits version: 0.3.5

**Comment by Izrab** [comment]
solved, but not sure how.
