### ISSUE TITLE
What is the correct version of Nodejs to use with Nativescript?

### ISSUE THREAD

**Issue by sn-sweet-stack** [EddyVerbruggen/nativescript-plugin-firebase#1291]
I get an error trying to install this plugin on Windows 10 with node 10.9.0

Basically I'm following this tutorial: 
https://medium.com/@groksrc/how-to-set-up-nativescript-vue-js-and-firebase-465354d4296b

Which means I've started with nativescript-vue/vue-cli-template and then run npm install. 
After that I do:

`tns plugin add nativescript-plugin-firebase`

And I get:

```
Support for Node.js 10.9.0 is not verified. This CLI might not install or run properly.


> nativescript-plugin-firebase@8.3.2 postinstall D:\Work\Trek\vuefirebasestarter\node_modules\nativescript-plugin-firebase
> node postinstall-hooks.js && node scripts/postinstall.js

Hook already installed: nativescript-plugin-firebase at location: D:\Work\Trek\vuefirebasestarter\hooks\before-prepare
Hook already installed: nativescript-plugin-firebase at location: D:\Work\Trek\vuefirebasestarter\hooks\after-prepare
D:\Work\Trek\vuefirebasestarter\node_modules\nativescript-plugin-firebase\scripts\postinstall.js:1215
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version:
Support for Node.js 10.9.0 is not verified. This CLI might not install or run properly.

3.1.3

    at new SemVer (D:\Work\Trek\vuefirebasestarter\node_modules\nativescript-plugin-firebase\scripts\postinstall.js:1215:11)
    at compare (D:\Work\Trek\vuefirebasestarter\node_modules\nativescript-plugin-firebase\scripts\postinstall.js:1488:10)
    at Function.gte (D:\Work\Trek\vuefirebasestarter\node_modules\nativescript-plugin-firebase\scripts\postinstall.js:1537:10)
    at Object.<anonymous> (D:\Work\Trek\vuefirebasestarter\node_modules\nativescript-plugin-firebase\scripts\postinstall.js:4182:86)
    at __webpack_require__ (D:\Work\Trek\vuefirebasestarter\node_modules\nativescript-plugin-firebase\scripts\postinstall.js:20:30)
    at D:\Work\Trek\vuefirebasestarter\node_modules\nativescript-plugin-firebase\scripts\postinstall.js:66:18
    at Object.<anonymous> (D:\Work\Trek\vuefirebasestarter\node_modules\nativescript-plugin-firebase\scripts\postinstall.js:69:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

What do I have to do to get this work? Is there a documented node version that is guaranteed to have support?

**Comment by EddyVerbruggen** [comment]
Sorry, but I don't think this plugin has to do with that error, check

https://www.google.com/search?q=%22This+CLI+might+not+install+or+run+properly%22&oq=%22This+CLI+might+not+install+or+run+properly%22&aqs=chrome..69i57.2089j0j7&sourceid=chrome&ie=UTF-8

**Comment by sn-sweet-stack** [comment]
Eddy, thanks for pointing me in the right direction. I truly didn't expect the problem to exist on a larger scale. It looks like NativeScript wants me to install the latest LTS version of Node. I visited nodejs.org and it looks like Node 10.16.0 is LTS now. I have upgraded my Nodejs it and this time the installation of nativescript-plugin-firebase went smooth.

**Comment by EddyVerbruggen** [comment]
Happy to hear that, thanks for reporting back!
