### ISSUE TITLE
Barcode scanner crashes with onFailureListener error on Android

### ISSUE THREAD

**Issue by nickdekkers** [EddyVerbruggen/nativescript-plugin-firebase#1321]
When I try to scan barcodes in quick succession, somewhere after around 15 scanned barcodes the app crashes with the following error:

```
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onPreviewFrame failed
System.err: 
System.err: Error: Cannot convert object to Lcom/google/android/gms/tasks/OnFailureListener; at index 0
System.err: File: "file:///data/data/io.neocles.dev/files/app/vendor.js, line: 130625, column: 29
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'onPreviewFrame', file:'file:///data/data/io.neocles.dev/files/app/vendor.js', line: 130625, column: 30
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err: 	at com.tns.gen.android.hardware.Camera_PreviewCallback.onPreviewFrame(Camera_PreviewCallback.java:19)
System.err: 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1225)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:214)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6986)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

I have been testing this on a Samsung Galaxy S9 running Android 9. I have also tested on iOS, just to be sure, but it does not crash on iOS. The scanner is able to easily scan more than 30 barcodes without crashing.

The code that triggers the crash is:
```
_this.camera.setPreviewCallbackWithBuffer(new android.hardware.Camera.PreviewCallback({
  onPreviewFrame: function (byteArray, camera) {
    if (_this.pendingFrameData !== null) {
      camera.addCallbackBuffer(_this.pendingFrameData.array());
      _this.pendingFrameData = null;
    }
    if (!_this.bytesToByteBuffer.has(byteArray)) {
      console.log("Skipping frame");
      return;
    }
    _this.pendingFrameData = _this.bytesToByteBuffer.get(byteArray);
    if (throttle++ % _this.processEveryNthFrame !== 0) {
      return;
    }
    var data = _this.pendingFrameData;
    if (_this.detector.processImage) {
      _this.lastVisionImage = com.google.firebase.ml.vision.common.FirebaseVisionImage.fromByteBuffer(data, metadata);
      _this.detector
        .processImage(_this.lastVisionImage)
        .addOnSuccessListener(onSuccessListener)
        .addOnFailureListener(onFailureListener);
    }
    else if (_this.detector.detectInImage) {
      _this.lastVisionImage = com.google.firebase.ml.vision.common.FirebaseVisionImage.fromByteBuffer(data, metadata);
      _this.detector
        .detectInImage(_this.lastVisionImage)
        .addOnSuccessListener(onSuccessListener)
        .addOnFailureListener(onFailureListener);
    }
    else {
      _this.runDetector(data, previewSize.width, previewSize.height);
    }
  }
}));
```
It crashes on the onFailureListener in the following if-statement (the bottom one in the snippet above):
```
if (_this.detector.detectInImage) {
  _this.lastVisionImage = com.google.firebase.ml.vision.common.FirebaseVisionImage.fromByteBuffer(data, metadata);
  _this.detector
    .detectInImage(_this.lastVisionImage)
    .addOnSuccessListener(onSuccessListener)
    .addOnFailureListener(onFailureListener);
}
```

**Comment by EddyVerbruggen** [comment]
I can't reproduce this, but I've added a `try .. catch` block around the offending code. Perhaps this helps in case it's a sporadic indicent.
