### ISSUE TITLE
crash while using markingMode: none

### ISSUE THREAD

**Issue by patrick-nurt** [EddyVerbruggen/nativescript-plugin-firebase#1353]
Hi Eddy,

After I've changed to using markingMode: none, my app keeps crashing with this error:

```JS: ERROR Error: Uncaught (in promise): EmptyError: no elements in sequence
System.err: com.tns.NativeScriptException: Attempt to use cleared object reference id=5392
System.err: 	at com.tns.Runtime.getJavaObjectByID(Runtime.java:1006)
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err: 	at com.tns.gen.com.google.android.gms.tasks.OnCompleteListener.onComplete(OnCompleteListener.java:19)
System.err: 	at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:214)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7094)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)```

**Comment by patrick-nurt** [comment]
I'm using the latest (9.0.4) of the nativescript-plugin-firebase plugin. It looks like this is where it goes bad: 
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/4c60759c2148fbcbde09f65868de0a828dc8b37c/src/firebase.android.ts#L591

I hope that it can be resolved quickly, as the markingMode really makes a huge difference here.

Best regards

**Comment by EddyVerbruggen** [comment]
Hi @patrick-nurt so this happens when you're using Remote Config on Android? And is it consistent when markingmode = none? I mean, does it happen every time? Then I can probably reproduce it and try to retain that listener a bit more aggressively.

**Comment by patrick-nurt** [comment]
Hmmm I remove markingmode = none, and it still happened, it doesnt happen everytime, but maybe 20% of the cases. I'm on NS 5.4.

**Comment by EddyVerbruggen** [comment]
Can you share your repo? I don’t see this happening with the demo app.

**Comment by jnorkus** [comment]
Hi @EddyVerbruggen . I am seeing the same issue.
```
Fatal Exception: com.tns.NativeScriptException: Attempt to use cleared object reference id=63
       at com.tns.Runtime.getJavaObjectByID(Runtime.java:1062)
       at com.tns.Runtime.callJSMethodNative(Runtime.java)
       at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
       at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
       at com.tns.Runtime.callJSMethod(Runtime.java:1160)
       at com.tns.Runtime.callJSMethod(Runtime.java:1138)
       at com.tns.Runtime.callJSMethod(Runtime.java:1134)
       at com.tns.gen.com.google.android.gms.tasks.OnCompleteListener.onComplete(OnCompleteListener.java:19)
       at com.google.android.gms.tasks.zzj.run(:4)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7063)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

Interestingly I can see 4 distinct object reference IDs and it seems they originate in different locations but all when starting the app. I can't be sure it's related to Remote Config but we do load the configs on app init.
