### ISSUE TITLE
Cloud Function call crashes app (iOS)

### ISSUE THREAD

**Issue by Sahkay** [EddyVerbruggen/nativescript-plugin-firebase#1456]
When calling my https callable cloud function from inside the app in the iOS simulator (at least that, havent tested real device or android), the app crashes with signal 11. Other APIs I am using from this plugin work fine including realtime database & authentication. I also did update to OSX Catalina recently so some stupid new apple "security feature" may have broken it but the other APIs I use still work. I have already tried the following:

- pod repo update
- deleting platforms folder
- simulator entitlements fix
- editing feature json file manually
- running setup script

**Code**
`const addMember = firebase.functions.httpsCallable("addNewMember");` (just below imports)
`addMember("hi").then((dataCue: any) => console.log(dataCue)).catch((error) => console.log(error));` (called on user input. Normally provides object with string & boolean properties instead of "hi". Both produce same error)

**Full Error**
`NativeScript caught signal 11.
Native Stack:
1   0x103c97cb1 sig_handler(int)
2   0x7fff518c9b1d _sigtramp
3   0x0
4   0x7fff518fdb85 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x7fff51901e58 _Unwind_RaiseException
6   0x7fff4f6df8bd __cxa_throw
7   0x7fff50864c44 _objc_exception_destructor(void*)
8   0x1031dc38d -[FIRFunctions URLWithName:]
9   0x1031dc84c -[FIRFunctions callFunction:withObject:timeout:context:completion:]
10  0x1031dc743 __59-[FIRFunctions callFunction:withObject:timeout:completion:]_block_invoke
11  0x1031de0db -[FUNContextProvider getContext:]
12  0x1031dc5dd -[FIRFunctions callFunction:withObject:timeout:completion:]
13  0x1031ddc67 -[FIRHTTPSCallable callWithObject:completion:]
14  0x104635fbd ffi_call_unix64
15  0x112a599c0
JS Stack:
callWithObjectCompletion([native code])
at file:///node_modules/nativescript-plugin-firebase/functions/functions.js:25:0
at ZoneAwarePromise(file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:0)
at file:///node_modules/nativescript-plugin-firebase/functions/functions.js:13:28
at newMember(file:///src/app/providers/user.ts:185:5)
at addMember(file:///src/app/admin/new-member/new-member.component.ts:35:23)
at
at callWithDebugContext(file:///node_modules/@angular/core/fesm5/core.js:30308:0)
at dispatchEvent(file:///node_modules/@angular/core/fesm5/core.js:19858:0)
at file:///node_modules/nativescript-angular/renderer.js:241:0
at onInvoke(file:///node_modules/@angular/core/fesm5/core.js:26255:0)
at run(file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:138:0)
at zonedCallback(file:///node_modules/nativescript-angular/renderer.js:240:0)
at notify(file:///node_modules/tns-core-modules/data/observable/observable.js:110:0)
at _emit(file:///node_modules/tns-core-modules/data/observable/observable.js:127:0)
at tap(file:///node_modules/tns-core-modules/ui/button/button.js:216:0)
at UIApplicationMain([native code])
at _start(file:///node_modules/tns-core-modules/application/application.js:295:0)
at run(file:///node_modules/tns-core-modules/application/application.js:323:0)
at bootstrapNativeScriptApp(file:///node_modules/nativescript-angular/platform-common.js:210:0)
at bootstrapApp(file:///node_modules/nativescript-angular/platform-common.js:111:0)
at bootstrapModule(file:///node_modules/nativescript-angular/platform-common.js:91:0)
at file:///app/bundle.js:1001:144
at ./main.ts(file:///app/bundle.js:1006:34)
at __webpack_requi<…>`

**Comment by Sahkay** [comment]
After testing on a real device the app does not crash outside of the simulator but now results in this error possibly relating to the firebase ios sdk.

`CONSOLE LOG file:///node_modules/@angular/core/fesm5/core.js:26256:0: Error: FIRFunctions app projectID cannot be nil.`

**Comment by Sahkay** [comment]
Fixed it by moving the const statement to just above the function call instead of just below the imports 🤦‍♂

**Comment by ngocnt1** [comment]
Hi @Sahkay  could you share the full fixed lines ?
My code:
`
const firebase = require("nativescript-plugin-firebase");
const hash = firebase.functions.httpsCallable("hashString");

hash("hashmenow")
            .then((dataCue: any) => console.log("Callable Function Result: " + dataCue.message))
            .catch((errorMessage: string) => console.log("Callable Function Error: " + errorMessage));
`
I got same threw exception as yours,
