### ISSUE TITLE
Probably question, maybe bug XD

### ISSUE THREAD

**Issue by MrPitty** [EddyVerbruggen/nativescript-plugin-firebase#1468]
I got error while saving data.
this code save the data successfull:
```javascript 
import * as firebase from "nativescript-plugin-firebase/firebase";

@Injectable()
export class MyExampleService {
public create(myObject: any): Promise<any> {
        return firebase.push(`${Path.DB_PATH.question}`, "").then(pushResult => {
            myObject.key = pushResult.key;
            firebase.setValue(`${Path.DB_PATH.question}/${myObject.key}`, JSON.stringify(myObject));
            return myObject;
        });
    }
}
```
this code dosen't work:
```javascript 
public create(myObject: any): Promise<any> {
        return firebase.push(`${Path.DB_PATH.question}`, myObject).then(pushResult => {
            myObject.key = pushResult.key;
            firebase.setValue(`${Path.DB_PATH.question}/${myObject.key}`, myObject);
            return myObject;
        });
    }
```
or 
still not working...
```javascript 
public create(myObject: any): Promise<any> {
        return firebase.push(`${Path.DB_PATH.question}`, '').then(pushResult => {
            myObject.key = pushResult.key;
            firebase.setValue(`${Path.DB_PATH.question}/${myObject.key}`, myObject);
            return myObject;
        });
    }
```

JS Stack:
setValueWithCompletionBlock([native code])
at file:///node_modules/nativescript-plugin-firebase/firebase.js:1187:0
at ZoneAwarePromise(file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:0)
at setValue(file:///node_modules/nativescript-plugin-firebase/firebase.js:1185:0)
at file:///src/app/services/my-example.service.ts:54:33

Package.json 
```json
"tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.1"
    },
"dependencies": {
    "@angular/animations": "8.2.6",
    "@angular/common": "8.2.6",
    "@angular/compiler": "8.2.6",
    "@angular/core": "8.2.6",
    "@angular/forms": "8.2.6",
    "@angular/platform-browser": "8.2.6",
    "@angular/platform-browser-dynamic": "8.2.6",
    "@angular/router": "8.2.6",
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "@nstudio/nativescript-snackbar": "1.0.0",
    "nativescript-angular": "8.2.1",
    "nativescript-camera": "^4.5.0",
    "nativescript-datetimepicker": "1.2.1",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-gif": "^4.0.2",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-ng-shadow": "2.1.0",
    "nativescript-plugin-firebase": "10.1.1",
    "nativescript-theme-core": "1.0.6",
    "reflect-metadata": "0.1.13",
    "rxjs": "6.5.3",
    "tns-core-modules": "6.1.2",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "~1.2.0",
    "typescript": "~3.5.3"
  },
```

**Comment by EddyVerbruggen** [comment]
Please share a repo I can clone and run.

**Comment by MrPitty** [comment]
> Please share a repo I can clone and run.

Already done

**Comment by EddyVerbruggen** [comment]
Let's continue in your repo.
