### ISSUE TITLE
'pod install' command failed.

### ISSUE THREAD

**Issue by koraykupe** [EddyVerbruggen/nativescript-plugin-firebase#1518]
Hi,

I installed the plugin, but when I run `npm tns run` I get this errors:

`Webpack compilation complete. Watching for file changes.
Webpack build done!
nativescript-plugin-firebase: /Users/admin_koray/Desktop/Sites/leisurehot-frontend-belvilla/platforms/ios/.pluginfirebaseinfo not found, forcing prepare!
nativescript-plugin-firebase: running release build or change in environment detected, forcing prepare!
Installing pods...
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    
Analyzing dependencies
Pre-downloading: `DKCarouselView` from `https://github.com/manijak/DKCarouselView`, tag `2.4.15`
Pre-downloading: `PocketSocket` from `https://github.com/NathanaelA/PocketSocket`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.3 (11C29)
         Git : git version 2.23.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target "leisurehotfrontendbelvilla" do
# Begin Podfile - /Users/admin_koray/Desktop/Sites/leisurehot-frontend-belvilla/node_modules/nativescript-carousel/platforms/ios/Podfile
pod 'DKCarouselView', :git => 'https://github.com/manijak/DKCarouselView', :tag => '2.4.15'

# End Podfile

# NativeScriptPlatformSection /Users/admin_koray/Desktop/Sites/leisurehot-frontend-belvilla/node_modules/nativescript-plugin-firebase/platforms/ios/Podfile with 9.0
platform :ios, '9.0'
# End NativeScriptPlatformSection

# Begin Podfile - /Users/admin_koray/Desktop/Sites/leisurehot-frontend-belvilla/node_modules/nativescript-plugin-firebase/platforms/ios/Podfile
# platform :ios, '9.0'

pod 'Firebase/Core', '~>6.13.0'

# Analytics
#pod 'Firebase/Analytics'

# Authentication
#pod 'Firebase/Auth'

# Realtime DB
#pod 'Firebase/Database'

# Cloud Firestore
#pod 'Firebase/Firestore'

# Remote Config
#pod 'Firebase/RemoteConfig'

# Performance Monitoring
#pod 'Firebase/Performance'

# Crashlytics
#pod 'Fabric'
#pod 'Crashlytics'


# Firebase Cloud Messaging (FCM)
pod 'Firebase/Messaging'

# Firebase In-App Messaging
pod 'Firebase/InAppMessagingDisplay'

# Firebase Cloud Storage
#pod 'Firebase/Storage'

# Firebase Cloud Functions
#pod 'Firebase/Functions'

# AdMob
#pod 'Firebase/AdMob'

# Dynamic Links
#pod 'Firebase/DynamicLinks'

# ML Kit
#pod 'Firebase/MLVision'
#pod 'Firebase/MLVisionTextModel'
#pod 'Firebase/MLVisionBarcodeModel'
#pod 'Firebase/MLVisionFaceModel'
#pod 'Firebase/MLVisionLabelModel'
#pod 'Firebase/MLVisionObjectDetection'
#pod 'Firebase/MLModelInterpreter'
#pod 'Firebase/MLVisionAutoML'
#pod 'Firebase/MLNaturalLanguage'
#pod 'Firebase/MLNLLanguageID'
#pod 'Firebase/MLNLTranslate'
#pod 'Firebase/MLCommon'
#pod 'Firebase/MLNLSmartReply'

# Facebook Authentication
#pod 'FBSDKCoreKit'
#pod 'FBSDKLoginKit'

# Google Authentication
#pod 'GoogleSignIn', '~> 5.0'
# End Podfile

# Begin Podfile - /Users/admin_koray/Desktop/Sites/leisurehot-frontend-belvilla/node_modules/tns-core-modules/platforms/ios/Podfile
# platform :ios, '9.0'
use_frameworks!

pod 'MaterialComponents/Tabs', '~> 92.3'
# End Podfile

# Begin Podfile - /Users/admin_koray/Desktop/Sites/leisurehot-frontend-belvilla/node_modules/nativescript-zip/platforms/ios/Podfile
pod 'SSZipArchive', '~> 2.2'

# End Podfile

# Begin Podfile - /Users/admin_koray/Desktop/Sites/leisurehot-frontend-belvilla/node_modules/nativescript-socket.io/platforms/ios/Podfile
pod 'Socket.IO-Client-Swift', '~> 12.1.3'
# End Podfile

# Begin Podfile - /Users/admin_koray/Desktop/Sites/leisurehot-frontend-belvilla/node_modules/nativescript-websockets/platforms/ios/Podfile
pod 'PocketSocket', :git => 'https://github.com/NathanaelA/PocketSocket'

# End Podfile

# Begin Podfile - /Users/admin_koray/Desktop/Sites/leisurehot-frontend-belvilla/node_modules/@nativescript/core/platforms/ios/Podfile
# platform :ios, '9.0'
use_frameworks!

pod 'MaterialComponents/Tabs', '~> 92.3'
# End Podfile
end
```

### Error

```
ArgumentError - invalid byte sequence in US-ASCII
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:283:in `split'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:283:in `block in ensure_versions_file_loaded'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:282:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:282:in `reduce'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:282:in `ensure_versions_file_loaded'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:204:in `search'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:165:in `search_for'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `sort_by'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:986:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=invalid+byte+sequence+in+US-ASCII&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Pod install fails on invalid byte sequence while having LANG=en_US.UTF-8 in profile
   https://github.com/CocoaPods/CocoaPods/issues/5780 [closed] [6 comments]
   4 weeks ago

 - Pod Install failed
   https://github.com/CocoaPods/CocoaPods/issues/9222 [closed] [3 comments]
   14 Oct 2019

 - Error while setting up CocoaPods
   https://github.com/CocoaPods/CocoaPods/issues/5979 [closed] [23 comments]
   06 Dec 2018

and 15 more at:
https://github.com/cocoapods/cocoapods/search?q=invalid%20byte%20sequence%20in%20US-ASCII&type=Issues&utf8=✓
'pod install' command failed.

admin_koray@EIN-MB-4073 leisurehot-frontend-belvilla % pod install
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    
[!] No `Podfile' found in the project directory.`

I am not sure if it is because of LANG variable, but I already added it to the profile file, but still shows the same warning.

Can you help me with that? I can provide more information if needed.

My dependencies:

`"@nstudio/nativescript-cardview": "^1.0.0",
    "core-js": "^3.3.2",
    "leisurehot-frontend-core": "file:../leisurehot-frontend-core",
    "moment": "^2.24.0",
    "nativescript-app-sync": "^2.0.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-laravel-echo": "^1.2.0",
    "nativescript-local-notifications": "^4.1.2",
    "nativescript-plugin-firebase": "^10.3.2",
    "nativescript-theme-core": "^2.0.24",
    "nativescript-ui-autocomplete": "^5.1.1",
    "nativescript-ui-dataform": "^5.1.1",
    "nativescript-ui-listview": "^7.1.0",
    "nativescript-ui-sidedrawer": "^7.0.4",
    "nativescript-urlhandler": "^1.3.0",
    "nativescript-vue": "^2.5.0-alpha.3",
    "nativescript-vue-lifecycle-hooks": "^1.0.0",
    "nativescript-vue-navigator": "^0.2.0",
    "sprintf-js": "^1.1.2",
    "tns-core-modules": "^6.2.3",
    "vue": "^2.6.10",
    "vuex": "^3.1.1"`

**Comment by ShrutiThakur01** [comment]
Hello ,

Have you found any solution for this problem?  I am also facing same issue.

TIA

**Comment by koraykupe** [comment]
Not completely, but I think it is because PhpStorm's terminal doesn't see the environment variables in .profile file. I tried with Terminal and it worked. I changed 'shell path' setting in Tools/Terminal settings on PhpStorm to > /bin/bash --rcfile ~/.bash_profile

You can also give a try.

**Comment by ShrutiThakur01** [comment]
Hello ,

Thank you very much for the response , will try this , do i need to run this in my project directory in terminal ?

TIA

**Comment by koraykupe** [comment]
@ShrutiThakur01 Yes, in the project directory.

**Comment by Mia12344** [comment]
i have the same issue how can i fix this 
any workaround ?
