### ISSUE TITLE
FCM token is in a wrong format for iOS

### ISSUE THREAD

**Issue by gsarme** [EddyVerbruggen/nativescript-plugin-firebase#1520]
Hi, I wrote my app with Nativescript + Angular. I want to send push notification to my device retrieving the push token from firebase and send the notification from my service.
Before upgrading to iOS 13 the notifications were sent and received correctly. 
I searched for the problem and I found that the push token for iOS is in this format

`{length=32,bytes=0x10fff92318d1f2e6785440f6168e56ad...00d3405325aa0620}`

How can I retrieve a correct push token? I tried to convert `0x10fff92318d1f2e6785440f6168e56ad...00d3405325aa0620` to base64 but it's not the solution because I haven't a correct base64 string

And if it's possible to gain the correct token , how can I check if the device has iOS 12 or iOS 13?

**Comment by gsarme** [comment]
I solved the problem doing:
`tns remove plugin nativescript-plugin-firebase`
`tns add plugin nativescript-plugin-firebase`
`tns remove platform ios`
Then I run `npm run config` under `node_modules/nativescript-plugin-firebase`

Now I'm facing another issue, the push token that I receive is a firebase token and not an APNs token so, if I try to send a push notification via `feedback.sandbox.push.apple.com` I receive nothing, and if I try to send the notification via firebase I get `success:1` from the response but the device displays nothing.

**Comment by EddyVerbruggen** [comment]
Can you share your repo so I can take a quick look?

**Comment by gsarme** [comment]
@EddyVerbruggen sorry, but I can't share the repo because it's not an open source project but I can show you some parts of the code and give you more information.

I'm using the 6.2.2 version of NativeScript with Angular.

In my _app.component.ts_ I have:
```JavaScript

firebase.init({
          showNotifications: true,
          showNotificationsWhenInForeground: true
      });
      messaging.registerForPushNotifications({
        onPushTokenReceivedCallback: (token: string): void => {
          console.log("Firebase plugin received a push token: " + token);
          localStorage.setItem("fcm_token", token);
          if(utils.ios){
            console.log("ios");
            localStorage.setItem("device_type", "ios");
          }else{
            console.log("android");
            localStorage.setItem("device_type", "android");
          }
        },

        onMessageReceivedCallback: (message: Message) => {
          console.log("Push message received: " + message.title);
        },

        // Whether you want this plugin to automatically display the notifications or just notify the callback. Currently used on iOS only. Default true.
        showNotifications: true,

        // Whether you want this plugin to always handle the notifications when the app is in foreground. Currently used on iOS only. Default false.
        showNotificationsWhenInForeground: true
      }).then(() => console.log("Registered for push"));
    }
``` 

This is my _firebase.nativescript.json_:
```JSON
{
    "using_ios": true,
    "using_android": true,
    "analytics": false,
    "firestore": false,
    "realtimedb": false,
    "authentication": false,
    "remote_config": false,
    "performance_monitoring": false,
    "external_push_client_only": true,
    "messaging": true,
    "in_app_messaging": false,
    "crashlytics": false,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "dynamic_links": false,
    "ml_kit": false
}
```
In my _package.json_ I have `"nativescript-plugin-firebase": "^10.3.2"`
In the _Info.plist_ file:
```xaml
        <key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
	</array>
	<key>UseExternalPushProvider</key>
	<true/>
```

Do you need more infos?

**Comment by EddyVerbruggen** [comment]
These lines in firebase.nativescript.json are mutually exclusive:  "external_push_client_only": true,
    "messaging": true

With `external_push_client_only` you would get an APNS token, and with `messaging` an FCM token. Please delete the file and run `npm i` again to restart the configurator.

**Comment by gsarme** [comment]
@EddyVerbruggen I didi what you said but now I have this error:

> CONSOLE ERROR file:///node_modules/@angular/core/fesm5/core.js:5847:0: ERROR Error: Uncaught (in promise): ReferenceError: Can't find variable: FIROptions
file:///node_modules/nativescript-plugin-firebase/firebase.js:279:0
at ZoneAwarePromise(file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:0)
at init(file:///node_modules/nativescript-plugin-firebase/firebase.js:261:0)
at ngOnInit(file:///src/app/app.component.ts:34:20)
at checkAndUpdateDirectiveInline(file:///node_modules/@angular/core/fesm5/core.js:19327:0)
at prodCheckAndUpdateNode(file:///node_modules/@angular/core/fesm5/core.js:28088:0)
at
at checkAndUpdateView(file:///node_modules/@angular/core/fesm5/core.js:27529:0)
at detectChanges(file:///node_modules/@angular/core/fesm5/core.js:18916:0)
at tick(file:///node_modules/@angular/core/fesm5/core.js:25185:0)
at _loadComponent(file:///node_modules/@angular/core/fesm5/core.js:25240:0)
at bootstrap(file:///node_modules/@angular/core/fesm5/core.js:25157:0)
at forEach([native code])
at _moduleDoBootstrap(file:///node_modules/@angular/core/fesm5/core.js:24872:0)
at file:///node_modules/@angular/core/fesm5/core.js:24840:0
at onInvoke(file:///node_modules/@angular/core/fesm5/core.js:24337:0)
at run(file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:138:0)
at file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:883:0
at onInvokeTask(file:///node_modules/@angular/core/fesm5/core.js:24328:0)
at runTask(file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:188:0)
at drainMicroTaskQueue(file:///ap<\M-b\M^@\M-&>

This is my _firebase.nativescript.json_ now:
```JSON
{
    "using_ios": true,
    "using_android": true,
    "analytics": false,
    "firestore": false,
    "realtimedb": false,
    "authentication": false,
    "remote_config": false,
    "performance_monitoring": false,
    "external_push_client_only": true,
    "messaging": false,
    "in_app_messaging": false,
    "crashlytics": false,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "dynamic_links": false,
    "ml_kit": false
}
```

Do you have any ideas why?

**Comment by EddyVerbruggen** [comment]
Perhaps try `rm -rf platforms node_modules` before rebuilding.

**Comment by gsarme** [comment]
I deleted the `node_modules, platforms, hooks` folders more than one time and then it worked. Thanks!

**Comment by BoHuCB** [comment]
Hi @EddyVerbruggen and @gsarme. I am following this thread and I have had the same issue. I believe I was getting FCM token (more than 100 characters long). After making the change with your information, now I am getting a token as "63c7b3a33252777eb58055d3a4b804ef6177dca64a1f7bfcb8a8722fa1dec54c". Then I tried to use this token to send push notifications on firebase cloud messaging, I can't never get any notifications. But when I try the same thing on Android it works. Do you guys have any idea why IOS wouldn't work?

**Comment by EddyVerbruggen** [comment]
@BoHuCB that looks like an APNs token. Try a tool like [Pusher](https://github.com/noodlewerk/NWPusher) to send a message to your device.

**Comment by BoHuCB** [comment]
@EddyVerbruggen Thanks for the quick response. I download Pusher but the company laptop doesn't allow me to use it since it is not from app store. But I guess, would FCM work if I use FCM to send a push notification by APNs token?

**Comment by EddyVerbruggen** [comment]
AFAIK you can't use an APNs token with FCM.

**Comment by BoHuCB** [comment]
@EddyVerbruggen That's what I figured. With this confirmation I think I just need to find a way to send the push notification to APNs to test it. Thank you very much for the responses.

**Comment by gsarme** [comment]
@BoHuCB if you can't use Pusher, try this [pushtry](https://pushtry.com/). This helped me.

**Comment by micaatt** [comment]
Got the same issue for android.
I followed the steps from [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase) and my firebase.nativescript.json looks like this:
```
{
  "using_ios": true,
  "using_android": true,
  "external_push_client_only": true
}
```
I'm using an external push running on both android and ios. The IOS seems to work fine however, in android, it keeps on returning a token with more than 100 characters. I'm using `onPushTokenReceivedCallback` for this. I also tried removing `hooks`, `platforms`, and `node_modules` and still got the same issue. I'm not sure if I miss anything. By the way, I'm using `nativescript-plugin-firebase: ^10.6.3` version.
