### ISSUE TITLE
NativeScript caught signal 11 for firebase.login on IOS

### ISSUE THREAD

**Issue by kaliseo** [EddyVerbruggen/nativescript-plugin-firebase#1521]
Hi, i'm trying to implement firebase login for facebook & Android on IOS, everything works on android, but in ios, app crashed with this error : 
For Facebook : 
NativeScript caught signal 11.
Native Stack:
1   0x108c58ba1 sig_handler(int)
2   0x7fff5245bb1d _sigtramp
3   0x0
4   0x7fff5248fb85 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x7fff52493e58 _Unwind_RaiseException
6   0x7fff502568bd __cxa_throw
7   0x7fff513fbc44 _objc_exception_destructor(void*)
8   0x109a862df +[FBSDKInternalUtility validateAppID]
9   0x109a86481 +[FBSDKInternalUtility validateURLSchemes]
10  0x109c0c4ee -[FBSDKLoginManager logInParametersWithPermissions:serverConfiguration:]
11  0x109c0d00e -[FBSDKLoginManager logIn]
12  0x109c0cdd5 -[FBSDKLoginManager logInWithPermissions:handler:]
13  0x109c0aed8 -[FBSDKLoginManager logInWithPermissions:fromViewController:handler:]
14  0x1095f1c3d ffi_call_unix64
15  0x110594660
JS Stack:
logInWithPermissionsFromViewControllerHandler([native code])
at file:///node_modules/nativescript-plugin-firebase/firebase.js:784:0
at initializePromise
at Promise([native code])
at login(file:///node_modules/nativescript-plugin-firebase/firebase.js:626:0)
at facebookLogin(file:///app/pages/login-page/login-page.js:17:0)
at notify(file:///node_modules/tns-core-modules/data/observable/observable.js:110:0)
at _emit(file:///node_modules/tns-core-modules/data/observable/observable.js:127:0)
at tap(file:///node_modules/tns-core-modules/ui/button/button.js:216:0)
at UIApplicationMain([native code])
at _start(file:///node_modules/tns-core-modules/application/application.js:295:0)
at run(file:///node_modules/tns-core-modules/application/application.js:323:0)
at file:///app/app.js:121:0
at ./app.js(file:///app/bundle.js:263:34)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at checkDeferredModules(file:///app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///app/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at promiseReactionJob

For Google : 
NativeScript caught signal 11.
Native Stack:
1   0x10a785ba1 sig_handler(int)
2   0x7fff5245bb1d _sigtramp
3   0x10af68383 JSC::ASTBuilder::Statement JSC::Parser<JSC::Lexer<unsigned short> >::parseStatementListItem<JSC::ASTBuilder>(JSC::ASTBuilder&, JSC::Identifier const*&, unsigned int*)
4   0x7fff5248fb85 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x7fff52493e58 _Unwind_RaiseException
6   0x7fff502568bd __cxa_throw
7   0x7fff513fbc44 _objc_exception_destructor(void*)
8   0x7fff23c710bc +[NSException raise:format:]
9   0x109cb66e5 -[GIDSignIn signInWithOptions:]
10  0x109cb601a -[GIDSignIn signIn]
11  0x10b11ec3d ffi_call_unix64
12  0x111e97c10
JS Stack:
signIn([native code])
at file:///node_modules/nativescript-plugin-firebase/firebase.js:860:0
at initializePromise
at Promise([native code])
at login(file:///node_modules/nativescript-plugin-firebase/firebase.js:626:0)
at googleLogin(file:///app/pages/login-page/login-page.js:83:0)
at notify(file:///node_modules/tns-core-modules/data/observable/observable.js:110:0)
at _emit(file:///node_modules/tns-core-modules/data/observable/observable.js:127:0)
at tap(file:///node_modules/tns-core-modules/ui/button/button.js:216:0)
at UIApplicationMain([native code])
at _start(file:///node_modules/tns-core-modules/application/application.js:295:0)
at run(file:///node_modules/tns-core-modules/application/application.js:323:0)
at file:///app/app.js:121:0
at ./app.js(file:///app/bundle.js:263:34)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at checkDeferredModules(file:///app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///app/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at promiseReactionJob

Here is a sample code where crash occured : 
`firebase.login({
      type: firebase.LoginType.GOOGLE,
      ios: {
        controller: topmost().ios.controller
      }
    }).then(function (result) {
      console.log(result);
    },
    function (errorMessage) {
      console.log("error", errorMessage);
    });`

Edit : here is my firebase.nativescript.json
{
    "using_ios": true,
    "using_android": true,
    "analytics": true,
    "firestore": false,
    "realtimedb": false,
    "authentication": true,
    "remote_config": false,
    "performance_monitoring": true,
    "external_push_client_only": false,
    "messaging": true,
    "in_app_messaging": true,
    "crashlytics": true,
    "storage": false,
    "functions": false,
    "facebook_auth": true,
    "google_auth": true,
    "admob": false,
    "dynamic_links": true,
    "ml_kit": false
}

**Comment by kaliseo** [comment]
It seems my Info.plist was wrong as i just added CFBundleURLName like a pig (got another one for deeplinks). Google works now, but not facebook. Searching for Facebook

**Comment by kaliseo** [comment]
Same for Facebook. I just had to wear my glasses.. Fixed

**Comment by MitchTalmadge** [comment]
Having a similar error:
```
NativeScript caught signal 11.
Native Stack:
1   0x108481ff1 sig_handler(int)
2   0x10d919b5d _sigtramp
3   0x10d84f000 _dyld_private
4   0x10d848b85 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x10d84ce58 _Unwind_RaiseException
6   0x10d3888bd __cxa_throw
7   0x10bff0c44 _objc_exception_destructor(void*)
8   0x10c1830bc +[NSException raise:format:]
9   0x107ba68a3 -[GIDSignIn signInWithOptions:]
10  0x107ba61d8 -[GIDSignIn signIn]
11  0x108e05edd ffi_call_unix64
12  0x13a0b2910
JS Stack:
signIn([native code])
at file:///node_modules/nativescript-plugin-firebase/firebase.js:821:0
at ZoneAwarePromise(file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:0)
at login(file:///node_modules/nativescript-plugin-firebase/firebase.js:620:0)
at file:///src/app/services/authentication.service.tns.ts:20:38
at step(file:///app/bundle.js:724:27)
at file:///app/bundle.js:699:75
at ZoneAwarePromise(file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:0)
at file:///app/bundle.js:695:36
at googleSignin(file:///src/app/shared/user-profile/user-profile.component.tns.ts:33:43)
at
at callWithDebugContext(file:///node_modules/@angular/core/fesm5/core.js:28411:0)
at dispatchEvent(file:///node_modules/@angular/core/fesm5/core.js:18085:0)
at file:///node_modules/nativescript-angular/renderer.js:241:0
at onInvoke(file:///node_modules/@angular/core/fesm5/core.js:24349:0)
at run(file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:138:0)
at zonedCallback(file:///node_modules/nativescript-angular/renderer.js:240:0)
at notify(file:///node_modules/tns-core-modules/data/observable/observable.js:110:0)
at _emit(file:///node_modules/tns-core-modules/data/observable/observable.js:127:0)
at tap(file:///node_modules/tns-core-modules/ui/button/button.js:216:0)
at UIApplicationMain([native code])
at _start(file:///node_modules/tns-core-modules/application/application.js:277:0)
at run(file:///node_modules/tns-core-modules/application/application.js:305:0)
at bootstrapNativeScriptApp(file:///node_modules/nativescript-angular/platform-common.js:205:0)
at bootstrapApp(file:///node_modules/nativescript-angular/platform-common.js:106:0<…>
```

Not sure what to do from here.
