### ISSUE TITLE
Firebase 10.3.2 - IconLoader: Could not find icon drawable from resource

### ISSUE THREAD

**Issue by cryptodude2000** [EddyVerbruggen/nativescript-plugin-firebase#1523]
I have been running version 9.0.2 without any issues. Today I decided to upgrade to version 10.3.2.

Doing that caused my App to top launching at the Splash Screen. No errors reported on the VStudio Terminal. It installs fine on both device and simulator. Both have the same behaviors. 

It throws this error:

12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
.
.
.
IconLoader: Could not find icon drawable from resource

I do not know what resource I am missing or what is going on here. I revert back to 9.0.2 and everything works fine on both simulator and device.

Do you require a Drawable for 10.3.2? What am I missing?

Running NS6.3

Partial Log below:

--------- beginning of crash
12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: Process: com.pantryon.pantryon, PID: 6520
12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$Client com.google.android.gms.common.api.Api$AbstractClientBuilder.buildClient(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.ClientSettings, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: 	at com.google.android.gms.common.api.GoogleApi.zaa(Unknown Source:93)
12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.<init>(Unknown Source:7)
12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.GoogleApiManager.zab(Unknown Source:43)
12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(Unknown Source:173)
12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: 	at com.google.android.gms.internal.base.zap.dispatchMessage(Unknown Source:8)
12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
12-21 01:20:09.946 10087  6520  6544 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-21 01:20:10.047  1000  1887  2916 W ActivityManager:   Force finishing activity com.pantryon.pantryon/com.tns.NativeScriptActivity
12-21 01:20:10.178 10087  6520  6544 I Process : Sending signal. PID: 6520 SIG: 9
12-21 01:20:10.184 10040  2936  5636 E s.nexuslaunche: No package ID ff found for ID 0xffffffff.
12-21 01:20:10.189 10040  2936  5636 E IconLoader: Could not find icon drawable from resource
12-21 01:20:10.189 10040  2936  5636 E IconLoader: android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at android.content.res.Resources.getDrawable(Resources.java:827)
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(SourceFile:118)
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(SourceFile:94)
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(SourceFile:325)
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(SourceFile:188)
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(SourceFile:173)
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at com.android.quickstep.RecentsModel.onTaskStackChangedBackground(SourceFile:214)
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(SourceFile:80)
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
12-21 01:20:10.189 10040  2936  5636 E IconLoader: 	at android.os.Binder.execTransact(Binder.java:731)
12-21 01:20:10.269  1000  1887  2923 I chatty  : uid=1000(system) Binder:1887_15 expire 8 lines
12-21 01:20:10.280  1000  1887  2469 I ActivityManager: Process com.pantryon.pantryon (pid 6520) has died: vis  +99TOP 
12-21 01:20:10.284  root  1725  1725 I Zygote  : Process 6520 exited due to signal (9)
12-21 01:20:10.291  1000  1724  1915 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.pantryon.pantryon#0
12-21 01:20:10.291  1000  1724  1915 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.pantryon.pantryon#0
12-21 01:20:10.303 10040  2936  2958 I s.nexuslaunche: NativeAlloc concurrent copying GC freed 9324(555KB) AllocSpace objects, 6(384KB) LOS objects, 50% free, 5MB/11MB, paused 16.429ms total 65.335ms

**Comment by MaxCavalheiro** [comment]
Same problem....

**Comment by TezzBhandari** [comment]
same issue. did anyone of you find answers
