### ISSUE TITLE
IOS crash on runtime

### ISSUE THREAD

**Issue by ittrad-mobile-lab** [EddyVerbruggen/nativescript-plugin-firebase#1546]
Even working on android emulator the same app is crashing on IOS simulator: ios8
Version 11.3.1 (SimulatorApp-912.5.1 SimulatorKit-570.3 CoreSimulator-681.17.2)

Why???!!! :(((

**MacBook-Pro:help2help ittradconsulting$ tns run ios --bundle**
Searching for devices...
Preparing project...
File change detected. Starting incremental webpack compilation...
webpack is watching the files…

Hash: 5a58b972c9906661e624
Version: webpack 4.27.1
Time: 9933ms
Built at: 
                                            Asset       Size                                          Chunks             Chunk Names
                                             0.js   95.1 KiB                                               0  [emitted]  
                                             1.js   57.4 KiB                                               1  [emitted]  
                                             2.js   11.3 KiB                                               2  [emitted]  
                                             3.js     11 KiB                                               3  [emitted]  
                                             4.js   11.1 KiB                                               4  [emitted]  
                                             5.js   11.3 KiB                                               5  [emitted]  
                                        bundle.js    406 KiB                                          bundle  [emitted]  bundle
                          fonts/fa-brands-400.ttf    131 KiB                                                  [emitted]  
                         fonts/fa-regular-400.ttf   39.1 KiB                                                  [emitted]  
                           fonts/fa-solid-900.ttf    204 KiB                                                  [emitted]  
                                     package.json  112 bytes                                                  [emitted]  
                                       runtime.js     73 KiB                                         runtime  [emitted]  runtime
tns_modules/tns-core-modules/inspector_modules.js  666 bytes  tns_modules/tns-core-modules/inspector_modules  [emitted]  tns_modules/tns-core-modules/inspector_modules
                                        vendor.js     19 MiB                                          vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
Entrypoint tns_modules/tns-core-modules/inspector_modules = runtime.js vendor.js tns_modules/tns-core-modules/inspector_modules.js
[../$$_lazy_route_resource lazy recursive] ../$$_lazy_route_resource lazy namespace object 160 bytes {bundle} [built]
[./app.scss] 121 KiB {bundle} [built]
[./app/app-routing.module.ts] 1.51 KiB {bundle} [built]
[./app/app.component.html] 3.3 KiB {bundle} [built]
[./app/app.component.ts] 3.04 KiB {bundle} [built]
[./app/app.module.ts] 1 KiB {bundle} [built]
[./app/auth/auth.guard.ts] 1.18 KiB {bundle} [built]
[./app/auth/auth.module.ts] 1.05 KiB {1} [built]
[./app/auth/auth.service.ts] 7.25 KiB {bundle} [built]
[./app/featured/featured.module.ts] 758 bytes {2} [built]
[./app/home/home.module.ts] 710 bytes {3} [built]
[./app/puzzle/puzzle.module.ts] 823 bytes {0} [built]
[./app/search/search.module.ts] 734 bytes {4} [built]
[./app/settings/settings.module.ts] 758 bytes {5} [built]
[./main.ts] 1.57 KiB {bundle} [built]
    + 824 hidden modules
Webpack compilation complete. Watching for file changes.
Webpack build done!
nativescript-plugin-firebase: building for same environment, not forcing prepare.
Project successfully prepared (ios)
Configure firebase
Successfully transferred all files on device D840681F-88D2-42B5-9671-8719297AC746.
Restarting application on device D840681F-88D2-42B5-9671-8719297AC746...
(RunningBoardServices) [com.apple.runningboard:connection] Identity resolved as application<org.nativescript.help2help>
CONSOLE INFO file:///node_modules/nativescript-dev-webpack/hot.js:3:0: HMR: Hot Module Replacement Enabled. Waiting for signal.
CONSOLE LOG file:///node_modules/@angular/core/fesm5/core.js:25638:0: Angular is running in the development mode. Call enableProdMode() to enable the production mode.

**NativeScript caught signal 6.
Native Stack:
1   0x102ea9481 sig_handler(int)
2   0x7fff5245b42d _sigtramp
3   0x1
4   0x7fff5234ba5c abort
5   0x7fff502497f8 __cxa_bad_cast
6   0x7fff502499c7 demangling_unexpected_handler()
7   0x7fff513fbd7c _objc_terminate()
8   0x7fff50256e97 std::__terminate(void (*)())
9   0x7fff50256e39 std::terminate()
10  0x7fff5223f7cd _dispatch_client_callout
11  0x7fff5224bc9b _dispatch_main_queue_callback_4CF
12  0x7fff23bd4049 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
13  0x7fff23bceca9 __CFRunLoopRun
14  0x7fff23bce066 CFRunLoopRunSpecific
15  0x7fff384c0bb0 GSEventRunModal
16  0x7fff48092d4d UIApplicationMain
17  0x10389ab4d ffi_call_unix64
18  0x10a4705d0
JS Stack:
UIApplicationMain([native code])
at run(file:///node_modules/@nativescript/core/application/application.js:312:0)
at file:///node_modules/@nativescript/angular/platform-common.js:210:0
at file:///node_modules/@nativescript/angular/platform-common.js:111:0
at file:///node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:608:144
at ./main.ts(file:///app/bundle.js:613:34)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at checkDeferredModules(file:///src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at
at asyncFunctionResume
at
at promiseReactionJob**

**Comment by ittrad-mobile-lab** [comment]
IOS: 
Add this KEY info.plist to test admob reward:
...
<key>GADApplicationIdentifier</key>
<string>ca-app-pub-3940256099942544~3347511713</string>
...

ANDROID:
Add this KEY AndroidManifest.xml to test admob reward:
<application ... >

<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713" />

<activity ...>

AT THE END:
firebase.admob.preloadRewardedVideoAd({
            testing: true,
            iosAdPlacementId: "ca-app-pub-3940256099942544/1712485313", // add your own
            androidAdPlacementId: "ca-app-pub-3940256099942544/5224354917", // add your own
            keywords: ["keyword1", "keyword2"] // add keywords for ad targeting
        });
