### ISSUE TITLE
IOS: Auth with facebook on simulator is not working

### ISSUE THREAD

**Issue by ittrad-mobile-lab** [EddyVerbruggen/nativescript-plugin-firebase#1560]
Following all the steps from here: 
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/AUTHENTICATION.md#facebook-login
I got the error below on IOS simulator.

It's crazy as on the android emulator EVERYTHING is working like a charm 👍 

What is going on? 
Any hint appreciated! 

`NativeScript caught signal 11.
Native Stack:
1   0x1080e6481 sig_handler(int)
2   0x7fff5245b42d _sigtramp
3   0x23158
4   0x7fff5248fb85 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x7fff52493e58 _Unwind_RaiseException
6   0x7fff502568bd __cxa_throw
7   0x7fff513fbc44 _objc_exception_destructor(void*)
8   0x108fa71f4 +[FBSDKInternalUtility validateURLSchemes]
9   0x10912d41e -[FBSDKLoginManager logInParametersWithPermissions:serverConfiguration:]
10  0x10912e04e -[FBSDKLoginManager logIn]
11  0x10912de15 -[FBSDKLoginManager logInWithPermissions:handler:]
12  0x10912bdb8 -[FBSDKLoginManager logInWithPermissions:fromViewController:handler:]
13  0x108ad7b4d ffi_call_unix64
14  0x116937300
JS Stack:
logInWithPermissionsFromViewControllerHandler([native code])
at file:///node_modules/nativescript-plugin-firebase/firebase.js:784:0
at ZoneAwarePromise(file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:902:0)
at file:///node_modules/nativescript-plugin-firebase/firebase.js:626:0
at file:///src/app/auth/auth.service.ts:41:23
at file:///src/app/auth/auth.component.ts:39:40
at
at callWithDebugContext(file:///node_modules/@angular/core/fesm5/core.js:30309:0)
at dispatchEvent(file:///node_modules/@angular/core/fesm5/core.js:19859:0)
at file:///node_modules/@nativescript/angular/renderer.js:241:0
at onInvoke(file:///node_modules/@angular/core/fesm5/core.js:26256:0)
at file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:138:0
at zonedCallback(file:///node_modules/@nativescript/angular/renderer.js:240:0)
at file:///node_modules/@nativescript/core/data/observable/observable.js:110:0
at file:///node_modules/@nativescript/core/data/observable/observable.js:127:0
at file:///node_modules/@nativescript/core/ui/button/button.js:216:0
at UIApplicationMain([native code])
at run(file:///node_modules/@nativescript/core/application/application.js:312:0)
at file:///node_modules/@nativescript/angular/platform-common.js:210:0
at file:///node_modules/@nativescript/angular/platform-common.js:111:0
at file:///node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:500:144
at ./main.ts(file:///app/bundle.js:505:34)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at checkDeferredModules(file:///src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///app/runt<…>`

**Comment by manojdcoder** [comment]
Did you try the demo app?
