### ISSUE TITLE
singleEvent: true errors out.

### ISSUE THREAD

**Issue by IvRRimum** [EddyVerbruggen/nativescript-plugin-firebase#172]
```
 22     firebase.query(
 23         "/profiles",
 24         {
 25             singleEvent: true,
 26             orderBy: {
 27                 type: firebase.QueryOrderByType.CHILD,
 28                 value: 'user_id'
 29             },  
 30                 
 31             range: {
 32                 type: firebase.QueryRangeType.EQUAL_TO,
 33                 value: this.userId
 34             },
 35   
 36             limit: {
 37                 type: firebase.QueryLimitType.LAST,
 38                 value: 1
 39             }
 40         }
 41     ).then((data) => {console.log("YUJUUUU")});
```

```
JS: EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'orderBy' of undefined
JS: ORIGINAL STACKTRACE:
JS: Error: Uncaught (in promise): TypeError: Cannot read property 'orderBy' of undefined
JS:     at resolvePromise (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:416:31)
JS:     at resolvePromise (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:401:17)
JS:     at /data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:449:17
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:223:37)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:6233:41)
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:222:42)
JS:     at Zone.runTask (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:123:47)
JS:     at drainMicroTaskQueue (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:355:35)
JS: Unhandled Promise rejection: Cannot read property 'orderBy' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'orderBy' of undefined TypeError: Cannot read property 'orderBy' of undefined
JS:     at /data/data/org.nativescript.test/files/app/tns_modules/nativescript-plugin-firebase/firebase.js:983:18
JS:     at new ZoneAwarePromise (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:465:29)
JS:     at Object.firebase.query (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-plugin-firebase/firebase.js:978:10)
JS:     at ProfileService.getUserData (/data/data/org.nativescript.test/files/app/services/profile.service.js:21:18)
JS:     at ProfileService.getUser (/data/data/org.nativescript.test/files/app/services/profile.service.js:17:14)
JS:     at new JobService (/data/data/org.nativescript.test/files/app/services/job.service.js:15:29)
JS:     at DebugAppView._View_Jobs_Host0.createInternal (Jobs_Host.ngfactory.js:22:26)
JS:     at DebugAppView.AppView.create (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9419:25)
JS:     at DebugAppView.create (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9631:48)
JS:     at ComponentFactory.create (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:6029:40)
JS: Error: Uncaught (in promise): TypeError: Cannot read property 'orderBy' of undefined
```

The problem is present only when using `singleEvent: true`.

**Comment by EddyVerbruggen** [comment]
Please check the signature of the `query` function, it's: `query(updateCallback, path, options)`

**Comment by IvRRimum** [comment]
@EddyVerbruggen But what about the then callback? It doesn't work?

**Comment by EddyVerbruggen** [comment]
It should, but can you please update the example to show what you're trying this time?

**Comment by IvRRimum** [comment]
```
 20   private getUserData(userId) {
 21     // TODO: Remove all data from photos$ observable, before pushing new values
 22     firebase.query(
 23         "/profiles",
 24         function() {},
 25         {
 26             singleEvent: true,
 27             orderBy: {
 28                 type: firebase.QueryOrderByType.CHILD,
 29                 value: 'user_id'
 30             },
 31             
 32             range: {
 33                 type: firebase.QueryRangeType.EQUAL_TO,
 34                 value: this.userId
 35             },
 36             
 37             limit: {
 38                 type: firebase.QueryLimitType.LAST,
 39                 value: 1
 40             }
 41         }
 42     ).then((data) => {console.log("YUJUUUU")});
 43   }
```

```
JS: EXCEPTION: Uncaught (in promise): Error: Cannot convert object to Ljava/lang/String; at index 0
JS: ORIGINAL STACKTRACE:
JS: Error: Uncaught (in promise): Error: Cannot convert object to Ljava/lang/String; at index 0
JS:     at resolvePromise (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:416:31)
JS:     at resolvePromise (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:401:17)
JS:     at /data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:449:17
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:223:37)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:6233:41)
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:222:42)
JS:     at Zone.runTask (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:123:47)
JS:     at drainMicroTaskQueue (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:355:35)
JS: Unhandled Promise rejection: Cannot convert object to Ljava/lang/String; at index 0 ; Zone: angular ; Task: Promise.then ; Value: Error: Cannot convert object to Ljava/lang/String; at index 0 Error: Cannot convert object to Ljava/lang/String; at index 0
JS:     at Error (native)
JS:     at /data/data/org.nativescript.test/files/app/tns_modules/nativescript-plugin-firebase/firebase.js:994:35
JS:     at new ZoneAwarePromise (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:465:29)
JS:     at Object.firebase.query (/data/data/org.nativescript.test/files/app/tns_modules/nativescript-plugin-firebase/firebase.js:978:10)
JS:     at ProfileService.getUserData (/data/data/org.nativescript.test/files/app/services/profile.service.js:21:18)
JS:     at ProfileService.getUser (/data/data/org.nativescript.test/files/app/services/profile.service.js:17:14)
JS:     at new JobService (/data/data/org.nativescript.test/files/app/services/job.service.js:15:29)
JS:     at DebugAppView._View_Jobs_Host0.createInternal (Jobs_Host.ngfactory.js:22:26)
JS:     at DebugAppView.AppView.create (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9419:25)
JS:     at DebugAppView.create (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9631:48)
JS: Error: Uncaught (in promise): Error: Cannot convert object to Ljava/lang/String; at index 0

```

@EddyVerbruggen

**Comment by IvRRimum** [comment]
````
 20   private getUserData(userId) {
 21     // TODO: Remove all data from photos$ observable, before pushing new values
 22     firebase.query(
 23         function() {},
 24         "/profiles",
 25         {
 26             singleEvent: true,
 27             orderBy: {
 28                 type: firebase.QueryOrderByType.CHILD,
 29                 value: 'user_id' 
 30             },  
 31             
 32             range: {
 33                 type: firebase.QueryRangeType.EQUAL_TO,
 34                 value: this.userId
 35             },  
 36             
 37             limit: {
 38                 type: firebase.QueryLimitType.LAST,
 39                 value: 1
 40             }   
 41         }   
 42     ).then((data) => {console.log("YUJUUUU")});
 43   }
```
This works :)

**Comment by EddyVerbruggen** [comment]
Yeah, that's the correct signature.

**Comment by IvRRimum** [comment]
@EddyVerbruggen but result is kinda wierd.
```
JS: {
JS:     "type": "ValueChanged",
JS:     "key": "profiles",
JS:     "value": [
JS:         null,
JS:         {
JS:             "attributes": {
JS:                 "-KSDVPAS81kbRfDmFf_8": "natasha",
JS:                 "-KR4tuuF46r4Rpp8JZO3": "Slim"
JS:             },
JS:             "is_public": true,
JS:             "path": "img_KDFbeXrOedf7b6NVRGMO0HDIFgx1.jpeg",
JS:             "lastname": "Dddream1337",
JS:             "firstname": "Out",
JS:             "extension": "jpeg",
JS:             "category_id": "KR4KOd0E4DdGsLrtp0g",
JS:             "user_id": "KDFbeXrOedf7b6NVRGMO0HDIFgx1"
JS:         }
JS:     ]
JS: }

```

Query is the same as above. but why there's the `null` value?

**Comment by IvRRimum** [comment]
@EddyVerbruggen Wierd thing is that when i change the fetched userId to the second user, i get normal result.

```
JS: {
JS:     "type": "ValueChanged",
JS:     "key": "profiles",
JS:     "value": [
JS:         {
JS:             "lastname": "Čudaddrs",
JS:             "firstname": "Kārlis",
JS:             "extension": "jpeg",
JS:             "attributes": {
JS:                 "-KSDVPAS81kbRfDmFf_8": "natasha",
JS:                 "-KR4tuuF46r4Rpp8JZO3": "fat"
JS:             },
JS:             "is_public": true,
JS:             "user_id": "6UAaCls5iSgavEtFE2qMX902Xmb2",
JS:             "path": "img_KDFbeXrOedf7b6NVRGMO0HDIFgx1.jpeg"
JS:         }
JS:     ]
JS: }
```

**Comment by IvRRimum** [comment]
My db structure:
http://prnt.sc/cvc64s
