### ISSUE TITLE
Application building without any errors on android but crashes when opened on phone and in emulator

### ISSUE THREAD

**Issue by blaur** [EddyVerbruggen/nativescript-plugin-firebase#174]
Hi guys,

I have followed all steps on android and the the build is successful. 

When the application is being loaded on the emulator or my physical phone (I have made sure to install play on the emulator).

There is no error messages  in any way and the last message in the log is:
```
Project successfully built
Successfully deployed on device with identifier '192.168.1.101:5555'.
```

This is my dependencies and versions:
  ```
 "tns-ios": {
      "version": "2.3.0"
    },
    "tns-android": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/platform-server": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "email-validator": "1.0.4",
    "moment": "2.13.0",
    "nativescript-angular": "0.4.0",
    "nativescript-iqkeyboardmanager": "1.0.1",
    "nativescript-loading-indicator": "^2.1.0",
    "nativescript-plugin-firebase": "^3.0.0",
    "nativescript-timedatepicker": "^0.2.2",
    "nativescript-unit-test-runner": "0.3.3",
    "nativescript-web-image-cache": "^2.0.1",
    "rxjs": "5.0.0-beta.6",
    "tns-core-modules": "^2.3.0",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "babel-traverse": "6.8.0",
    "babel-types": "6.8.1",
    "babylon": "6.8.0",
    "filewalker": "0.1.2",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-jasmine": "^1.0.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "nativescript-dev-webpack": "0.0.20",
    "typescript": "^1.8.10"
  }

```
Any suggestions that could guide me the right direction? Without any error messages it is difficult to debug.

**Comment by EddyVerbruggen** [comment]
Have you tried running `adb logcat` in a command prompt? That should give you the stacktrace.

**Comment by nithinshiriya** [comment]
Here is the crash report.

```
--------- beginning of crash
E/AndroidRuntime( 2309): FATAL EXCEPTION: main
E/AndroidRuntime( 2309): Process: org.nativescript.PicPollANS, PID: 2309
E/AndroidRuntime( 2309): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.
E/AndroidRuntime( 2309):        at android.app.ActivityThread.installProvider(ActivityThread.java:5002)
E/AndroidRuntime( 2309):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594)
E/AndroidRuntime( 2309):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
E/AndroidRuntime( 2309):        at android.app.ActivityThread.access$1500(ActivityThread.java:151)
E/AndroidRuntime( 2309):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
E/AndroidRuntime( 2309):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2309):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2309):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 2309):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2309):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2309):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 2309):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 2309): Caused by: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.
E/AndroidRuntime( 2309):        at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
E/AndroidRuntime( 2309):        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
E/AndroidRuntime( 2309):        at android.app.ActivityThread.installProvider(ActivityThread.java:4999)
E/AndroidRuntime( 2309):        ... 11 more
W/ActivityManager(  855):   Force finishing activity 1 org.nativescript.PicPollANS/com.tns.NativeScriptActivity
```

**Comment by nithinshiriya** [comment]
Adding below line to build.gradle [platform/android] would run your app. 

```
	defaultConfig {
		minSdkVersion 17
		targetSdkVersion computeTargetSdkVersion()
		applicationId  "Your app identification id"	
	}
```
