### ISSUE TITLE
TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor

### ISSUE THREAD

**Issue by prasadbeligala** [EddyVerbruggen/nativescript-plugin-firebase#1791]
Hi, I reinstalled Nativescript and added the plugin again, but the following error occurs even only inserting just the require statement. "var firebase = require("@nativescript/firebase").firebase;".
Any fixes please?

TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
File: (file:///data/user/0/org.nativescript.preview/files/app/vendor.js:5048:37)

StackTrace:
(file:///data/user/0/org.nativescript.preview/files/app/vendor.js:5048:38)
        at ../node_modules/@nativescript/firebase/mlkit/mlkit-cameraview-common.js(file:///data/user/0/org.nativescript.preview/files/app/vendor.js:5105:30)
        at __webpack_require__(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:817:30)
        at fn(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:121:20)
        at (file:///data/user/0/org.nativescript.preview/files/app/vendor.js:5117:82)
        at ../node_modules/@nativescript/firebase/mlkit/mlkit-cameraview.js(file:///data/user/0/org.nativescript.preview/files/app/vendor.js:5472:30)
        at __webpack_require__(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:817:30)
        at fn(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:121:20)
        at (file:///data/user/0/org.nativescript.preview/files/app/vendor.js:5956:75)
        at ../node_modules/@nativescript/firebase/mlkit/textrecognition/textrecognition-common.js(file:///data/user/0/org.nativescript.preview/files/app/vendor.js:5979:30)
        at __webpack_require__(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:817:30)
        at fn(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:121:20)
        at (file:///data/user/0/org.nativescript.preview/files/app/vendor.js:5810:81)
        at ../node_modules/@nativescript/firebase/mlkit/textrecognition/index.js(file:///data/user/0/org.nativescript.preview/files/app/vendor.js:5943:30)
        at __webpack_require__(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:817:30)
        at fn(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:121:20)
        at (file:///data/user/0/org.nativescript.preview/files/app/vendor.js:4921:120)
        at ../node_modules/@nativescript/firebase/mlkit/index.js(file:///data/user/0/org.nativescript.preview/files/app/vendor.js:4963:30)
        at __webpack_require__(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:817:30)
        at fn(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:121:20)
        at (file:///data/user/0/org.nativescript.preview/files/app/vendor.js:854:64)
        at ../node_modules/@nativescript/firebase/firebase-common.js(file:///data/user/0/org.nativescript.preview/files/app/vendor.js:1091:30)
        at __webpack_require__(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:817:30)
        at fn(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:121:20)
        at (file:///data/user/0/org.nativescript.preview/files/app/vendor.js:1108:74)
        at ../node_modules/@nativescript/firebase/firebase.js(file:///data/user/0/org.nativescript.preview/files/app/vendor.js:3563:30)
        at __webpack_require__(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:817:30)
        at fn(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:121:20)
        at (file:///data/user/0/org.nativescript.preview/files/app/bundle.js:167:16)
        at ./app.js(file:///data/user/0/org.nativescript.preview/files/app/bundle.js:197:30)
        at __webpack_require__(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:817:30)
        at checkDeferredModules(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:44:23)
        at webpackJsonpCallback(file:///data/user/0/org.nativescript.preview/files/app/runtime.js:31:19)
        at (file:///data/user/0/org.nativescript.preview/files/app/bundle.js:2:57)
        at require(:1:266)

**Comment by slayer3600** [comment]
Duplicate of #1790
