### ISSUE TITLE
General error during semantic analysis: Unsupported class file major version 61

### ISSUE THREAD

**Issue by emog** [EddyVerbruggen/nativescript-plugin-firebase#1850]
Dependencies: 

   "@nativescript/core": "~8.1.3",
    "@nativescript/firebase": "^11.1.3",
    "@nativescript/android": "8.1.1",
    "@nativescript/ios": "~8.1.0",

Error:
* Where:
Settings file '/Users/egeorgiev/AppDevelopment/vnmarketresearch/vnmarket/platforms/tempPlugin/firebase/settings.gradle'

* What went wrong:
Could not compile settings file '/Users/egeorgiev/AppDevelopment/vnmarketresearch/vnmarket/platforms/tempPlugin/firebase/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
  
  java.lang.IllegalArgumentException: Unsupported class file major version 61
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)

**Comment by csimpi** [comment]
UPDATE:

@emog You need to downgrade your JDK version.

Install JDK 8
`sudo apt install openjdk-8-jdk`

Change the default version of JDK selecting from the appearing list:
`sudo update-alternatives --config java`

**Comment by emog** [comment]
@csimpi Thank you. I'm using macOS but I will downgrade the jdk version and will try again.
