### ISSUE TITLE
Firebase Messaging crash issue in Android 13

### ISSUE THREAD

**Issue by pauline-webpuppies** [EddyVerbruggen/nativescript-plugin-firebase#1889]
Hi,

We recently released a new version of our app  with targetSdkVersion 31.
Firebase Crashlytics reported the following crash (triggered by an Android 13 device):
`Fatal Exception: java.lang.IllegalArgumentException: com.MaxiCash.ipayment: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
       at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
       at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:484)
       at android.app.PendingIntent.getActivity(PendingIntent.java:470)
       at android.app.PendingIntent.getActivity(PendingIntent.java:434)
       at com.google.firebase.messaging.CommonNotificationBuilder.createContentIntent(com.google.firebase:firebase-messaging@@20.3.0:125)
       at com.google.firebase.messaging.CommonNotificationBuilder.createNotificationInfo(com.google.firebase:firebase-messaging@@20.3.0:27)
       at com.google.firebase.messaging.CommonNotificationBuilder.createNotificationInfo(com.google.firebase:firebase-messaging@@20.3.0:9)
       at com.google.firebase.messaging.DisplayNotification.handleNotification(com.google.firebase:firebase-messaging@@20.3.0:27)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@20.3.0:65)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@20.3.0:44)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@20.3.0:27)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@20.3.0:17)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@20.3.0:43)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
       at java.lang.Thread.run(Thread.java:1012)`

![image](https://user-images.githubusercontent.com/84489115/220278999-7f14c10c-2f57-4394-8b4a-45d7e7c01729.png)

We found a similar issue here but it was triggered by Android 12 device and they fixed it by releasing a new version:
[https://github.com/firebase/firebase-android-sdk/issues/3115](url)

Nativescript CLI: 8.4.0
@nativescript/android version: 8.3.1
@nativescript/firebase version: 11.1.3

What should we do to resolve this?
Appreciate any help, thank you.

**Comment by pichurichko** [comment]
+1 Experiencing the same issue as described above

**Comment by pichurichko** [comment]
@pauline-webpuppies try to use this plugin, it works with Android 13 and has better support:

https://github.com/NativeScript/firebase

**Comment by joeytitans** [comment]
@pauline-webpuppies Did you find a resolution?  We are experiencing the same crashes - luckily the crashes seem to be occurring in the background after a notification is received, but still an annoyance nevertheless.

**Comment by pauline-webpuppies** [comment]
@pichurichko thanks, we will try it out. Did you use any custom configurations to make it work?

@joeytitans unfortunately no, we'll try @pichurichko's suggestion and see if that works

**Comment by pichurichko** [comment]
@pauline-webpuppies just change targetSdkVersion to 33 for android build. Everything else works as expected and described in readme.
See demos for details (if you use angular pay attention to the place of firebase initialisation).
