### ISSUE TITLE
firebase.login() throwing onclick error

### ISSUE THREAD

**Issue by ianhaggerty** [EddyVerbruggen/nativescript-plugin-firebase#276]
I've done my best to fix this, but the solution completely eludes me. I've got a click handler on a login button which delegates to my `AuthService`:

```
login(user: LoginCredentials): Observable<User> {
    if (this.isLoggedIn) {
        return Observable.create((observer) => observer.next(this.currentUser))
    }

    return Observable.fromPromise(
        firebase.login({
            type: firebase.LoginType.PASSWORD,
            ...user
        })
    );
}
```

When executed, gives:

```An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException:
Calling js method onClick failed

[object Object]
File: "file:///data/data/org.nativescript.Groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js, line: 12760, column: 20

StackTrace:
        Frame: function:'DebugAppView._rethrowWithContext', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12760, column: 21
        Frame: function:'', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12777, column: 27
        Frame: function:'', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/nativescript-angular/renderer.js', line: 213, column: 26
        Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 190, column: 28
        Frame: function:'onInvoke', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4391, column: 41
        Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 189, column: 34
        Frame: function:'Zone.run', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 83, column: 43
        Frame: function:'NgZone.run', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4260, column: 66
        Frame: function:'zonedCallback', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/nativescript-angular/renderer.js', line: 212, column: 24
        Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/data/observable/observable.js', line: 149, column: 23
        Frame: function:'Observable._emit', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/data/observable/observable.js', line: 168, column: 18
        Frame: function:'onClick', file:'file:///data/data/org.nativescript.Groceries/files/app/tns_modules/ui/button/button.js', line: 35, column: 32


        at com.tns.Runtime.callJSMethodNative(Native Method)
        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
        at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
        at com.tns.Runtime.callJSMethod(Runtime.java:1047)
        at com.tns.Runtime.callJSMethod(Runtime.java:1028)
        at com.tns.Runtime.callJSMethod(Runtime.java:1018)
        at com.tns.gen.android.view.View_OnClickListener.onClick(android.view.View$OnClickListener.java)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I don't know if this is some weird race condition in my main.ts file:

```
import { platformNativeScriptDynamic } from "nativescript-angular/platform";
import firebase = require("nativescript-plugin-firebase");
import { AuthStateData } from "nativescript-plugin-firebase";
import { Observable } from "rxjs";

import { AppModule } from "./app.module";

platformNativeScriptDynamic().bootstrapModule(AppModule);

/*
 * Authentication State Observable
 *
 * Do NOT subscribe to this. This is subscribed to by AuthService when injected as a singleton
 * into the root of the application (app.module.ts).
 */
export const authState$: Observable<AuthStateData> = Observable.create((observer) => {
    firebase.init({
        onAuthStateChanged: observer.next.bind(observer)
    }).then(
        (instance) => console.log("firebase.init done"),
        (error) => console.log("firebase.init error: ", error)
    );
});
```

I'm aware there have been similar issues raised, but nothing suggested seems to work. Any help would be appreciated.

**Comment by ianhaggerty** [comment]
*It's worth mentioning that logging out and registering new users is working just fine. It's just the login button that is throwing this.

**Comment by ianhaggerty** [comment]
Well, I managed to fix this. Just changed

```
firebase.login({
            type: firebase.LoginType.PASSWORD,
            ...user
        })
```

to

```
firebase.login({
    type: firebase.LoginType.PASSWORD,
    email: user.email,
    password: user.password
})
```

I'm no expert on Typescript, but the spread operator seems to be breaking integration with this plugin.

**Comment by EddyVerbruggen** [comment]
@ianhaggerty not-a-typescript-expert here too. I can see what you're doing but I don't think the plugin can be changed to change that behaviour. If anyone know please send a PR.
