### ISSUE TITLE
Error: EEXIST: file already exists, symlink '../pegjs/bin/pegjs'

### ISSUE THREAD

**Issue by imaginationcoder** [EddyVerbruggen/nativescript-plugin-firebase#308]
Hi,
I am using Angular 2 and 
 nativescript │ 2.4.2         
  tns-ios      │ 2.4.0  
Followed the instructions as mentioned in plugin but I am getting below error when run
`# tns livesync ios --watch`
can you please help in resolving this issue?

 

```
** BUILD SUCCEEDED **

Project successfully built
Transferring project files...
shell.js: internal error
Error: EEXIST: file already exists, symlink '../pegjs/bin/pegjs' -> '/Users/maisapride7/Library/Developer/CoreSimulator/Devices/82E87AE5-5CC4-4D5A-8E3B-729D6A610C77/data/Containers/Bundle/Application/023CCBEA-1CC6-4DBB-9A9C-BE46C3936C3B/tingrnsapp.app/app/tns_modules/nativescript-plugin-firebase/node_modules/xcode/node_modules/.bin/pegjs'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:76:10)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at /usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:183:9
    at Array.forEach (native)
    at Object._cp (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:157:11)
    at Object.cp (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/common.js:186:23)
    at IOSSimulatorFileSystem.transferDirectory (/usr/local/lib/node_modules/nativescript/lib/common/mobile/ios/simulator/ios-simulator-file-system.js:33:42)
    at /usr/local/lib/node_modules/nativescript/lib/services/livesync/platform-livesync-service-base.js:104:49
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
```

**Comment by EddyVerbruggen** [comment]
I have no idea what `pegjs` is.. perhaps blow away `node_modules` and `platform/ios` and try again..

**Comment by imaginationcoder** [comment]
@EddyVerbruggen 
yes its working  when removed node_modules and reinstalled by adding plugin as package dependency.
Removed node_modules and platforms/ios
and added plugin to package.json instead of 'tns plugin add ...'
`"nativescript-plugin-firebase": "^3.10.2"`
then
```
 npm install
 tns platform add ios@2.4.0
 tns livesync ios --watch
```
Thank you very much for your quick reply.
