### ISSUE TITLE
Application crash each time I send push notification message

### ISSUE THREAD

**Issue by rkhayyat** [EddyVerbruggen/nativescript-plugin-firebase#335]
I'm trying to enable firebase messaging on android, I uncommented the included.gradle as mentioned.

Each time I sent a message from Firebase the application crash and I get this error message:

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to instantiate service org.nativescript.plugins.firebase.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: /data/app/com.rachid.alkhayat-1.apk
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2597)
	at android.app.ActivityThread.access$1700(ActivityThread.java:152)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5328)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: /data/app/com.rachid.alkhayat-1.apk
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2588)

**Comment by EddyVerbruggen** [comment]
Looks like you need to do a tns build android and/or remove and readd the platform folder.

**Comment by rkhayyat** [comment]
Thanks Eddy, it worked, actually I downloaded the plugin manually, then I did remove/add android then I did build, and it worked
