### ISSUE TITLE
AOT build failing with Error in firebase.addValueEventListener: TypeError: Cannot read property 'child' of null

### ISSUE THREAD

**Issue by Salahudeen** [EddyVerbruggen/nativescript-plugin-firebase#350]
The regular build successfully passes and login works perfectly fine. The AOT build fails at runtime while trying to fetch data.

JS: Error in firebase.addValueEventListener: TypeError: Cannot read property 'child' of null
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'child' of null
JS: TypeError: Cannot read property 'child' of null
JS:     at file:///data/data/com.infosys.jobcard/files/app/bundle.js:27161:24
JS:     at new ZoneAwarePromise (file:///data/data/com.infosys.jobcard/files/app/vendor.js:58514:29)
JS:     at Object.module.exports.Array.concat.firebase.addValueEventListener

**Comment by EddyVerbruggen** [comment]
Any idea how to fix it?
