### ISSUE TITLE
Query : range not working when value is number

### ISSUE THREAD

**Issue by GrEg00z** [EddyVerbruggen/nativescript-plugin-firebase#438]
Old issue : #87 

I don't understant why, but the problem comes back for me, exactly in the same context than my previous post in issue 87 :

> Same problem here, while using this :
> 
> firebase.query(({ type, key, value }) => {
>         // .......
>       }, ref, {
>          orderBy: {
>           type: firebase.QueryOrderByType.CHILD,
>           value: 'status'
>             ......................................

So if I use number value instead of string value in **ranges** array , I get the following error : 

```
TypeError: Cannot read property 'isStopped' of undefined
	at Subscriber.error (file:///data/data/org.nativescript..../files/app/tns_modules/rxjs/Subscriber.js:100:18)
	at ZoneDelegate.invoke (file:///data/data/org.nativescript..../files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:365:26)
	at Object.onInvoke (file:///data/data/org.nativescript...../files/app/tns_modules/@angular/core/bundles/core.umd.js:4132:37)
	at ZoneDelegate.invoke (file:///data/data/org.nativescript..../files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:364:32)
	at Zone.run (file:///data/data/org.nativescript..../files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:125:43)
	at file:///data/data/org.nativescript..../files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:760:57
	at ZoneDelegate.invokeTask (file:///data/data/org.nativescript..../files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:398:31)
	at Object.onInvokeTask (file:///data/data/org.nativescript..../files/app/tns_modules/@angular/core/bundles/core.umd.js:4123:37)
	at ZoneDelegate.invokeTask (file:///data/data/org.nativescript..../files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:397:36)
	at Zone.runTask (file:///data/data/org.nativescript..../files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:165:47)
	at drainMicroTaskQueue (file:///data/data/org.nativescript..../files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:593:35)

```

I've updated to 4.0.3, I get the same problem.

If I use **range** instead of **ranges**, then it only working with string value.
While using number value, there is no error thrown, but no data are received

The problem seems to come only when we have numeric value in firebase data, and try to request on this properties

**Comment by ivanwitzke** [comment]
For me it happens the same when using booleans too, no matters if using `range` or `ranges`...

        firebase.query(data => {
            console.log(data.key, JSON.stringify(data.value))
        }, '/category', {
                orderBy: {
                    type: firebase.QueryOrderByType.CHILD,
                    value: 'deleted'
                },
                ranges: [{
                    type: firebase.QueryRangeType.EQUAL_TO,
                    value: false
                }],
            });

**Comment by ivanwitzke** [comment]
found #328 which seems to be related...
