### ISSUE TITLE
Failed to build metadata

### ISSUE THREAD

**Issue by YonatanKra** [EddyVerbruggen/nativescript-plugin-firebase#452]
After installing the plugin and solving #451, I get this error during the run process:
```
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class android.support.v7.cardview.BuildConfig conflict: \Groceries\platforms\android\build\intermed
iates\exploded-aar\com.android.support\cardview-v7\26.0.0-alpha1\jars\classes.jar and \Groceries\platforms\android\build\intermediates\exploded-aar\com.android.su
pport\cardview-v7\25.3.1\jars\classes.jar
        at com.telerik.metadata.ClassRepo.addToCache(ClassRepo.java:21)
        at com.telerik.metadata.Builder.build(Builder.java:38)
        at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_92\bin\java.exe'' finished with non-zero exit value 1
```

**Comment by YonatanKra** [comment]
Ok - should have figured that on my own. For some reason the platform included a 25.3.1 folders, which created the issue.  Just deleted the 25.3.1 folders and everything's good.
