### ISSUE TITLE
OutOfMemory Error on physical Android device

### ISSUE THREAD

**Issue by d3mac123** [EddyVerbruggen/nativescript-plugin-firebase#504]
I am getting this crash on my Android device (works fine on both iOS and Android Simulators plus iOS devices) - any ideas?

System.err: com.tns.NativeScriptException: 
System.err: Calling js method onDataChange failed
System.err: Error: java.lang.OutOfMemoryError: Failed to allocate a 11315274 byte allocation with 4166144 free bytes and 8MB until OOM
System.err:     java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
System.err:     java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:133)
System.err:     java.lang.StringBuffer.append(StringBuffer.java:126)
System.err:     java.io.StringWriter.write(StringWriter.java:135)
System.err:     com.google.gson.stream.JsonWriter.beforeName(JsonWriter.java:614)
System.err:     com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:401)
System.err:     com.google.gson.stream.JsonWriter.value(JsonWriter.java:527)
System.err:     com.google.gson.Gson$1.write(Gson.java:293)
System.err:     com.google.gson.Gson$1.write(Gson.java:278)
System.err:     com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
System.err:     com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
System.err:     com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
System.err:     com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
System.err:     com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
System.err:     com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
System.err:     com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
System.err:     com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
System.err:     com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
System.err:     com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
System.err:     com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
System.err:     com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
System.err:     com.google.gson.Gson.toJson(Gson.java:669)
System.err:     com.google.gson.Gson.toJson(Gson.java:648)
System.err:     com.google.gson.Gson.toJson(Gson.java:603)
System.err:     com.google.gson.Gson.toJson(Gson.java:583)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err:     com.tns.gen.com.google.firebase.database.ValueEventListener.onDataChange(ValueEventListener.java:11)
System.err:     com.google.firebase.database.zzp.onDataChange(Unknown Source)
System.err:     com.google.android.gms.internal.zzdtt.zza(Unknown Source)
System.err:     com.google.android.gms.internal.zzdvo.zzbur(Unknown Source)
System.err:     com.google.android.gms.internal.zzdvu.run(Unknown Source)
System.err:     android.os.Handler.handleCallback(Handler.java:815)
System.err:     android.os.Handler.dispatchMessage(Handler.java:104)
System.err:     android.os.Looper.loop(Looper.java:207)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5765)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
System.err: File: "file:///data/data/com.asouza.ppgFinder/files/app/tns_modules/nativescript-plugin-firebase/firebase.js, line: 151, column: 29
System.err: StackTrace: 
System.err: 	Frame: function:'firebase.toJsObject', file:'file:///data/data/com.asouza.ppgFinder/files/app/tns_modules/nativescript-plugin-firebase/firebase.js', line: 151, column: 30
System.err: 	Frame: function:'firebase.getCallbackData', file:'file:///data/data/com.asouza.ppgFinder/files/app/tns_modules/nativescript-plugin-firebase/firebase.js', line: 194, column: 21
System.err: 	Frame: function:'onDataChange', file:'file:///data/data/com.asouza.ppgFinder/files/app/tns_modules/nativescript-plugin-firebase/firebase.js', line: 1683, column: 33
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err: 	at com.tns.gen.com.google.firebase.database.ValueEventListener.onDataChange(ValueEventListener.java:11)
System.err: 	at com.google.firebase.database.zzp.onDataChange(Unknown Source)
System.err: 	at com.google.android.gms.internal.zzdtt.zza(Unknown Source)
System.err: 	at com.google.android.gms.internal.zzdvo.zzbur(Unknown Source)
System.err: 	at com.google.android.gms.internal.zzdvu.run(Unknown Source)
System.err: 	at android.os.Handler.handleCallback(Handler.java:815)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:104)
System.err: 	at android.os.Looper.loop(Looper.java:207)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5765)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
System.err: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 11315274 byte allocation with 4166144 free bytes and 8MB until OOM
System.err: 	at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
System.err: 	at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:133)
System.err: 	at java.lang.StringBuffer.append(StringBuffer.java:126)
System.err: 	at java.io.StringWriter.write(StringWriter.java:135)
System.err: 	at com.google.gson.stream.JsonWriter.beforeName(JsonWriter.java:614)
System.err: 	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:401)
System.err: 	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:527)
System.err: 	at com.google.gson.Gson$1.write(Gson.java:293)
System.err: 	at com.google.gson.Gson$1.write(Gson.java:278)
System.err: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
System.err: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
System.err: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
System.err: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
System.err: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
System.err: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
System.err: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
System.err: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
System.err: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
System.err: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
System.err: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
System.err: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
System.err: 	at com.google.gson.Gson.toJson(Gson.java:669)
System.err: 	at com.google.gson.Gson.toJson(Gson.java:648)
System.err: 	at com.google.gson.Gson.toJson(Gson.java:603)
System.err: 	at com.google.gson.Gson.toJson(Gson.java:583)
System.err: 	... 18 more
ActivityManager: Process com.asouza.ppgFinder (pid 11826) has died

**Comment by dbeulen** [comment]
On which device are you testing? The app is trying to allocate around 10 MB, which shouldn't be too bad. Also, what makes you think it is related to this plugin?

**Comment by d3mac123** [comment]
No images. Just a bunch of records containing tons of gps data.
