### ISSUE TITLE
FIrebase Messages Error since 5.0.2

### ISSUE THREAD

**Issue by RaphaelJenni** [EddyVerbruggen/nativescript-plugin-firebase#566]
Firebase Messages causing some problems. I don't use them in my app, so I haven't loaded them, but I get this error:

```
System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/nativescript/plugins/firebase/MyFirebaseMessagingService;
System.err:     at org.nativescript.plugins.firebase.FirebasePluginLifecycleCallbacks.onActivityResumed(FirebasePluginLifecycleCallbacks.java:48)
System.err:     at android.app.Application.dispatchActivityResumed(Application.java:216)
System.err:     at android.app.Activity.onResume(Activity.java:1251)
System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
System.err:     at android.app.Activity.performResume(Activity.java:6783)
System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3406)
System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3469)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732)
System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: Caused by: java.lang.ClassNotFoundException: org.nativescript.plugins.firebase.MyFirebaseMessagingService
System.err:     at java.lang.VMClassLoader.findLoadedClass(Native Method)
System.err:     at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     ... 16 more
System.err: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
System.err:     ... 16 more
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.APP.APPCode-1/base.apk"],nativeLibraryDirectories=[/data/app/com.APP.APPCode-1/lib/x86, /data/app/com.APP.APPCode-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     ... 16 more

```

**Comment by EddyVerbruggen** [comment]
Oh.. I think `FirebasePluginLifecycleCallbacks` requires a guard..

**Comment by EddyVerbruggen** [comment]
5.0.4 is on npm, thanks for reporting it!

**Comment by RaphaelJenni** [comment]
That was fast! Thanks allot!
