### ISSUE TITLE
Android app crashes when receiving push notification message from Firebase console.

### ISSUE THREAD

**Issue by sma5802** [EddyVerbruggen/nativescript-plugin-firebase#599]
Hello Eddy,

I am using the latest version 5.1.2.

When I use the Firebase Console to send out a test message, my android app crashes on a samsung s6 device, both running and not running the app.  I followed your readme line by line, also found this issue: #423 with the exact error message.  But I have not had any success.

Is there anything that you want me to try?

Thank you very much for your hardwork!

Here's the detailed message:

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to instantiate service org.nativescript.plugins.firebase.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.A2ZFieldServices.FieldCompass-1/base.apk"],nativeLibraryDirectories=[/data/app/com.A2ZFieldServices.FieldCompass-1/lib/arm, /data/app/com.A2ZFieldServices.FieldCompass-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3449)
            at android.app.ActivityThread.-wrap6(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1721)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:6682)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.A2ZFieldServices.FieldCompass-1/base.apk"],nativeLibraryDirectories=[/data/app/com.A2ZFieldServices.FieldCompass-1/lib/arm, /data/app/com.A2ZFieldServices.FieldCompass-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3446)
            ... 8 more
            Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
                        at java.lang.VMClassLoader.findLoadedClass(Native Method)
                        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                        ... 10 more
            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.A2ZFieldServices.FieldCompass-1/base.apk"],nativeLibraryDirectories=[/data/app/com.A2ZFieldServices.FieldCompass-1/lib/arm, /data/app/com.A2ZFieldServices.FieldCompass-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                        ... 13 more

**Comment by GeetsKrish** [comment]
Hi Eddy,

I'm also facing the same issue while integrating this plugin in Nativescript-Vue Project.
I am using the plugin version 5.2.0

Unable to instantiate service org.nativescript.plugins.firebase.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/org.nativescript.FirebaseApp1-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.FirebaseApp1-1/lib/x86, /vendor/lib, /system/lib]]
System.err: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2746)
System.err: 	at android.app.ActivityThread.access$1800(ActivityThread.java:151)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:135)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.plugins.firebase.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/org.nativescript.FirebaseApp1-1/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.FirebaseApp1-1/lib/x86, /vendor/lib, /system/lib]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
System.err: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2743)
System.err: 	... 9 more
System.err: 	Suppressed: java.lang.NoClassDefFoundError: org.nativescript.plugins.firebase.MyFirebaseMessagingService
System.err: 		at dalvik.system.DexFile.defineClassNative(Native Method)
System.err: 		at dalvik.system.DexFile.defineClass(DexFile.java:226)
System.err: 		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
System.err: 		at dalvik.system.DexPathList.findClass(DexPathList.java:321)
System.err: 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
System.err: 		... 12 more
System.err: 	Suppressed: java.lang.ClassNotFoundException: org.nativescript.plugins.firebase.MyFirebaseMessagingService
System.err: 		at java.lang.Class.classForName(Native Method)
System.err: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
System.err: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
System.err: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
System.err: 		... 11 more
System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
ActivityManager: Process org.nativescript.FirebaseApp1 (pid 12792) has died

**Comment by EddyVerbruggen** [comment]
Is there a repo I can clone?

Make sure you've removed the platforms/android folder after adding the plugin.

**Comment by GeetsKrish** [comment]
Hi Eddy,

I have removed the platforms/android folder after adding the plugin and executed **tns run android**

Here is sample repo url :
[link is here](https://github.com/GeetsKrish/Nativescript-Vue-Firebase)

Firebase init was success, but onPushTokenReceivedCallback was never called.
App crashes if push notification is received from firebase console.

Thanks in advance..

**Comment by karthikbalu** [comment]
True, I too have this problem and my version is 6.4.0

**Comment by danaric** [comment]
Hello,

I made a test up with all major versions sinde 5.2+ until 6.0 and everything was crashing up. So, after that I tested up the version nativescript-plugin-firebase@5.0.4 and everything seems working very well! :)

**Comment by JaganJonnala** [comment]
+1
