### ISSUE TITLE
Best practice to init firebase

### ISSUE THREAD

**Issue by shabib3** [EddyVerbruggen/nativescript-plugin-firebase#613]
Hi guys,

I am trying to get what is the right way to init firebase (I am working on Angular project).

In the beginning I've put the `firebase.init()` in the `main.ts` but after I started to work on IOS I didn't received a background messaging on IOS so the thing that did the work for me was or to put the `firebase.init()` on 1000ms timeout on `main.ts` or to put it on the first page that I route to.

The thing is that I want to make the user login as he open the app, like this:
```
firebase.getAuthToken({ forceRefresh: false }).then(token => {
    if (!token) {
        return;
    }
    this._loginUtils.loginFromToken(token);
}, err => {
    firebase.logout();
    console.log("There is no token saved in the device");
});
```

Now, the thing is that the `setTimeout` solution is an ugly solution, but it works just fine, but when I implements the "prettier" solution of putting the `init` function on the first page `ngOnInit` function the init function never resolved, and I'll explain:
This is the "prettier" solution (exactly as @EddyVerbruggen wrote in the demo):
```
ngOnInit(): void {
    firebase.init({
        onAuthStateChanged: function (data) { // optional but useful to immediately re-logon the user when he re-visits your app
            console.log(data.loggedIn ? "Logged in to firebase" : "Logged out from firebase");
            if (data.loggedIn) {
                console.log("user's email address: " + (data.user.email ? data.user.email : "N/A"));
            }
            }
    }).then(() => {
        firebase.getAuthToken({ forceRefresh: false }).then(token => {
            if (!token) {
                return;
            }
            this._loginUtils.loginFromToken(token);
        }, err => {
            firebase.logout();
            console.log("There is no token saved in the device");
        });
    })
}
```  

The buggy issue here is that the `init` function never resolved.

After debug the actual code of `init` function in `firebase` module in those two situation I found out that the following:

- when putting the init inside the first component in looks like it gets to this line `appModule.on(appModule.launchEvent, runInit);` but it seems like the `appModule.launchEvent` never raise or already raised, so the firebase init never happen and it is never resolved, so the use cannot automatically login into the app.

- when putting it in the `main.ts` with `setTimeout` it looks like it gets to this line `runInit();` and all works just fine but this is a very ugly and bad performance solution.

PLS!
What is the right way to init the firebase?

Thanks a lot :)

**Comment by ShawnPavel** [comment]
I have been using this plugin for well over a year now in an angular app. And I have always called the `firebase.init` function in the `ngOnInit` method within the `app.component`. It has always worked flawlessly. However since I upgraded to NativeScript 3.4, Angular 5, and plugin v5.1.3 I have been encountering the same issues you have.

Primarily the init function never resolves and any calls to firebase after that result in a `run init first` error.

It seems there are a few others having similar issues with running init first.
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/612
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/593
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/588
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/585

It seems the consensus so far is the use the timeout method. 
@EddyVerbruggen Is there anything we can do to help figure out why we need that timeout now?

**Comment by EddyVerbruggen** [comment]
Updating the embedded demo-ng app to 5.2.0 and will see what `ngOnInit` in `app.component` does.

**Comment by EddyVerbruggen** [comment]
@ShawnPavel I've moved my init code to `app.components.ts` and still see this log message after startup: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/f07762ddea6d0760f2e55ce2703ad652cf74bf4c/demo-ng/app/app.component.ts#L15

Perhaps your init is different, so can you replace yours with mine and see if we can narrow this down?

**Comment by ShawnPavel** [comment]
@EddyVerbruggen I dropped in your init directly replacing mine, and the "Firebase Initialized" is never printed.

**Comment by EddyVerbruggen** [comment]
Interesting.. at this point we can do one of 2 things:

1. You `git clone https://github.com/EddyVerbruggen/nativescript-plugin-firebase`, `cd nativescript-plugin-firebase/src`, and `npm run demo-ng.ios`
2. You give me instructions how to run your project :)

**Comment by ShawnPavel** [comment]
I'll try one first.

**Comment by EddyVerbruggen** [comment]
OK, if that works we'll need to dig into your project I'm afraid.

**Comment by ShawnPavel** [comment]
I will say, that I've done all this testing to this point on Android.

**Comment by ShawnPavel** [comment]
@EddyVerbruggen I can confirm that your initialization as well as my old initialization code work fine on iOS. So this appears to be an Android related issue.

**Comment by EddyVerbruggen** [comment]
Oww, the OP mentioned iOS so I focused on that. I'll take a look at Android.

**Comment by ShawnPavel** [comment]
@EddyVerbruggen I attempted to run the android demo but I get an error:

```
Could not merge source set folders: 
[app/tns_modules/long/dist/long.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/long/dist/long.min.js       [app/tns_modules/long/dist/long.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/long/dist/long.min.js.gz: Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf.min.js.gz        [app/tns_modules/protobufjs/dist/protobuf.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf.min.js: Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf-light.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf-light.min.js.gz    [app/tns_modules/protobufjs/dist/protobuf-light.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf-light.min.js: Error: Duplicate resources
[app/tns_modules/bytebuffer/dist/bytebuffer.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer.min.js.gz    [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer.min.js: Error: Duplicate resources
[app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js.gz  [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js: Error: Duplicate resources
        at com.android.ide.common.res2.DataSet.checkItems(DataSet.java:466)
        at com.android.ide.common.res2.DataSet.loadFromFiles(DataSet.java:258)
        at com.android.ide.common.res2.AssetSet.loadFromFiles(AssetSet.java:30)
        at com.android.build.gradle.tasks.MergeSourceSetFolders.doFullTaskAction(MergeSourceSetFolders.java:104)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:88)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeF0DebugAssets'.
> [app/tns_modules/long/dist/long.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/long/dist/long.min.js     [app/tns_modules/long/dist/long.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/long/dist/long.min.js.gz: Error: Duplicate resources
  [app/tns_modules/protobufjs/dist/protobuf.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf.min.js.gz      [app/tns_modules/protobufjs/dist/protobuf.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf.min.js: Error: Duplicate resources
  [app/tns_modules/protobufjs/dist/protobuf-light.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf-light.min.js.gz  [app/tns_modules/protobufjs/dist/protobuf-light.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf-light.min.js: Error: Duplicate resources
  [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer.min.js.gz  [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer.min.js: Error: Duplicate resources
  [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js.gz        [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] /Users/shawnpavel/Development/other/test/nativescript-plugin-firebase/demo-ng/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js: Error: Duplicate resources
```

**Comment by EddyVerbruggen** [comment]
Yeah got that one as well and fixed it locally.

Better yet I found the culprit with NativeScript 3.4 and this plugin on Android:
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/f07762ddea6d0760f2e55ce2703ad652cf74bf4c/src/firebase.android.ts#L353

The `foregroundActivity` used to be defined in NativeScript < 3.4 when your OnInit function runs, but that's no longer the case. This fact also bit me in 3 other plugins unfortunately and I didn't realise this one was affected as well.

Fix inbound!

**Comment by rahultyagiji** [comment]
Eddy I am still getting this error... I am using version 5.1.5 and natievscript 3.4... Not sure what I am doing wrong there.

**Comment by rahultyagiji** [comment]
Sorry guys, I am not sure if it is working for others? Can someone please confirm that this has worked for android?? I am happy to provide more details regarding code and error. @EddyVerbruggen

**Comment by eleventhaus** [comment]
Getting this error on NS 3.4.1 // Firebase plugin 5.1.8

I have firebase require in main.ts and call firebase init in app.cmp OnInit but keep getting the duplicate resource error from protobufs. What am I missing?

Main.ts
```
import { platformNativeScriptDynamic } from "nativescript-angular/platform";

import { AppModule } from "./app.module";

require("nativescript-plugin-firebase");

platformNativeScriptDynamic().bootstrapModule(AppModule);
```

app.component.ts
```
import { Component, OnInit } from "@angular/core";

import { firebase } from 'nativescript-plugin-firebase/firebase-common';
import { AuthService } from '@sunnypets/core';

@Component({
    selector: "ns-app",
    templateUrl: "app.component.html"
})
export class AppComponent implements OnInit {

    constructor(private _as: AuthService) { }

    ngOnInit() {
        firebase.init({
            //persist should be set to false as otherwise numbers aren't returned during livesync
            persist: false,
            storageBucket: 'gs://sunny-pets-184721.appspot.com',
            onAuthStateChanged: (data: any) => {
                console.log(JSON.stringify(data));
                if (data.loggedIn) {
                    AuthService.uid = data.user.uid;
                }
            }
        }).then(
            function (instance) {
                console.log("firebase.init done");
            },
            function (error) {
                console.log("firebase.init error: " + error);
            }
        );
    }

}
```

Error:
```
* What went wrong:
Execution failed for task ':app:mergeF0F1DebugAssets'.
> [app/tns_modules/protobufjs/dist/protobuf-light.min.js] /Users/volaticus/Dev/tns/sunnypetstns/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf-light.min.js.gz  [app/tns_modules/protobufjs/dist/protobuf-light.min.js] /Users/volaticus/Dev/tns/sunnypetstns/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf-light.min.js: Error: Duplicate resources
  [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] /Users/volaticus/Dev/tns/sunnypetstns/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer.min.js.gz  [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] /Users/volaticus/Dev/tns/sunnypetstns/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer.min.js: Error: Duplicate resources
  [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] /Users/volaticus/Dev/tns/sunnypetstns/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js.gz        [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] /Users/volaticus/Dev/tns/sunnypetstns/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js: Error: Duplicate resources
  [app/tns_modules/long/dist/long.min.js] /Users/volaticus/Dev/tns/sunnypetstns/platforms/android/app/src/main/assets/app/tns_modules/long/dist/long.min.js     [app/tns_modules/long/dist/long.min.js] /Users/volaticus/Dev/tns/sunnypetstns/platforms/android/app/src/main/assets/app/tns_modules/long/dist/long.min.js.gz: Error: Duplicate resources
  [app/tns_modules/protobufjs/dist/protobuf.min.js] /Users/volaticus/Dev/tns/sunnypetstns/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf.min.js.gz      [app/tns_modules/protobufjs/dist/protobuf.min.js] /Users/volaticus/Dev/tns/sunnypetstns/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf.min.js: Error: Duplicate resources
```

[gist](https://gist.github.com/eleventhaus/6e11ac674fad170e1c317e10570aa0b8.js)

**Comment by shabib3** [comment]
@eleventhaus - try to import firebase like this `import { firebase } from 'nativescript-plugin-firebase';` instead of `import { firebase } from 'nativescript-plugin-firebase/firebase-common';` in the `AppComponent`

**Comment by eleventhaus** [comment]
My ide throws an error for no exported member when using `import { firebase } from 'nativescript-plugin-firebase';`

```
app/app.component.ts(3,10): error TS2305: Module '"/Users/volaticus/Dev/tns/sunnypetstns/node_modules/nativescript-plugin-firebase/index"' has no exported member 'firebase'.
```

Also tried use `const = require('nativescript-plugin-firebase');` but got same duplicate resources error as before

**Comment by shabib3** [comment]
@eleventhaus - try this - `import * as firebase from "nativescript-plugin-firebase";`

**Comment by eleventhaus** [comment]
Same as original error :S

I appreciate the help!! Any other ideas?

**Comment by rahultyagiji** [comment]
I have used, 
import {firebase} from "nativescript-plugin-firebase/firebase-common" in appcomponent. 
that worked for me. But mine is 3.4.0 and 5.1.7...

**Comment by rafaelcmrj** [comment]
same error here, tried all different versions... any update on this?

**Comment by reytum** [comment]
Same error here but in different plugin, its gives duplicate resource error for semver.min.js and semver.min.js.gz. Any help on this would be appreciated.

**Comment by rafaelcmrj** [comment]
I'm still getting this error when I update any HTML/sass file. Do we have the right way to init the app in the documentation?
