### ISSUE TITLE
I can't build the project after adding the plugin

### ISSUE THREAD

**Issue by mschakulat** [EddyVerbruggen/nativescript-plugin-firebase#64]
I get the following error, if i want to build it for android:

`:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class com.tns.internal.AppBuilderCallback conflict: /Users/mschakulat/stuff/nativescript/myapp/platforms/android/build/intermediates/classes/F0F1/debug and /Users/mschakulat/stuff/nativescript/myapp/platforms/android/build/intermediates/classes/F0/debug
        at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
        at com.telerik.metadata.Builder.build(Builder.java:42)
        at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
`

**Comment by EddyVerbruggen** [comment]
Did you try removing and re-adding the android platform?

**Comment by yogeshwar607** [comment]
I am just building it for iOS platform, after successful build , i run my
app and when i click on init button , then it gives this error.
Same behavior for your demo app and the app i created for testing .

**Comment by EddyVerbruggen** [comment]
@yogeshwar607 wrong issue?
