### ISSUE TITLE
Error: com.tns.NativeScriptException: Failed to find module: "nativescript-plugin-firebase/firebase-common", relative to: app/tns_modules/

### ISSUE THREAD

**Issue by dbilovd** [EddyVerbruggen/nativescript-plugin-firebase#649]
Hello, I'm new to Nativescript.
I was trying out this plugin for nativescript-vue and I ran into this issue. Haven't been able to progress beyond.
Help needed. Thanks.

PS: I've attached my screenshots below.

![screen shot 2018-03-21 at 9 11 40 pm](https://user-images.githubusercontent.com/968842/37737735-9ff88600-2d4c-11e8-9f09-dc37e9298a9c.png)
![screen shot 2018-03-21 at 9 12 21 pm](https://user-images.githubusercontent.com/968842/37737736-a04c891c-2d4c-11e8-88fd-96a0b7d21eea.png)
![screen shot 2018-03-21 at 9 12 31 pm](https://user-images.githubusercontent.com/968842/37737738-a0a58e68-2d4c-11e8-90c9-7e826b35c834.png)

**Comment by EddyVerbruggen** [comment]
Please share a repo and link it here.

**Comment by dbilovd** [comment]
@EddyVerbruggen I found the issue.
Gradle was complaining about id "com.google.gms...." not being found. I noticed my google-services.json file wasn't in the `build` dir in `dist` and that led me to find out that hooks weren't copied automatically from `/hooks` to `dist/hooks`. I copied the hooks there and ran `npm run watch:android` again and it worked this time. Thanks.

**Comment by GiboMac** [comment]
Can you re-open?
I've followed the examples to initialize the plugin, but same error occurs:

tns version 4.0.0

```

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-plugin-firebase/firebase-common", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
    android.app.ActivityThread.-wrap1(Unknown Source:0)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
    android.os.Handler.dispatchMessage(Handler.java:105)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6541)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 223507
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 167177
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'o', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 165856
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 132667
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-plugin-firebase/firebase-common", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
    android.app.ActivityThread.-wrap1(Unknown Source:0)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
    android.os.Handler.dispatchMessage(Handler.java:105)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6541)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 223507
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 167177
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'o', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 165856
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 132667
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-plugin-firebase/firebase-common", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
    android.app.ActivityThread.-wrap1(Unknown Source:0)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
    android.os.Handler.dispatchMessage(Handler.java:105)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6541)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 223507
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 167177
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'o', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 165856
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 132667
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-plugin-firebase/firebase-common", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
    android.app.ActivityThread.-wrap1(Unknown Source:0)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
    android.os.Handler.dispatchMessage(Handler.java:105)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6541)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 223507
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 167177
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'o', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 165856
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 132667
	Frame: function:'t', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.devinterface.errbit_mobile/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:530)
	at com.tns.Runtime.run(Runtime.java:522)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
	... 8 more

```

**Comment by EddyVerbruggen** [comment]
Please share a repo and link it here.

**Comment by GiboMac** [comment]
Thanks! https://github.com/GiboMac/errbit-mobile

**Comment by endytc** [comment]
I have same issue and after copied hooks to dist/hoost I'm get error. 
Thank's.
![image](https://user-images.githubusercontent.com/1209684/40952703-8b3c01fc-68a6-11e8-82d5-1e3400e1b348.png)

**Comment by shriharip** [comment]
@EddyVerbruggen I have the same issue. 

Using Nativescript Vue

Repo link https://github.com/shriharip/vuedrive.git

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-plugin-firebase/firebase-common", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:553)
    com.tns.Runtime.run(Runtime.java:545)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5254)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
File: "<unknown>, line: 1, column: 265
....
