### ISSUE TITLE
Error when tapping on a push - {N}-Vue

### ISSUE THREAD

**Issue by rigoparis** [EddyVerbruggen/nativescript-plugin-firebase#723]
Hey guys!

I've been using your plugin to test it on {N}-Vue and hopefully use it on a future production app.

Anyways, the plugin works almost perfectly. I'm just encountering an issue, whenever the app is minimized or closed and I tap on received push notification, the app crashes.

Just want to point out this happens only when the app is minimized or closed.

The error that comes up is:
```
System.err: com.tns.NativeScriptException: 
System.err: Calling js method run failed
System.err: Error: java.lang.NoSuchFieldError: no "I" field "BYTES" in class "Ljava/lang/Long;" or its superclasses
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err:     android.os.Handler.handleCallback(Handler.java:739)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:234)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5526)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
System.err: File: "file:///data/data/com.ciriscr.trakapp/files/app/app.js, line: 1, column: 131311
System.err: StackTrace: 
System.err: 	Frame: function:'Ho', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 131312
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 131223
System.err: 	Frame: function:'Mc', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 181875
System.err: 	Frame: function:'No', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 131199
System.err: 	Frame: function:'Ho', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 131598
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 131223
System.err: 	Frame: function:'Mc', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 181875
System.err: 	Frame: function:'No', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 131199
System.err: 	Frame: function:'Ho', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 131598
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 131223
System.err: 	Frame: function:'Mc', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 181875
System.err: 	Frame: function:'No', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 131199
System.err: 	Frame: function:'yo', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 129108
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 194438
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 194404
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 542855
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.trakapp/files/app/app.js', line: 1, column: 248852
System.err: 	Frame: function:'invoke', file:'file:///data/data/com.ciriscr.trakapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err: 	Frame: function:'run', file:'file:///data/data/com.ciriscr.trakapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:234)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
System.err: Caused by: java.lang.NoSuchFieldError: no "I" field "BYTES" in class "Ljava/lang/Long;" or its superclasses
System.err: 	... 14 more
ActivityManager: Process com.ciriscr.trakapp (pid 13170) has died
```

My environment is:
```
npm version
{ 'trakapp-movil': '1.3.4',
  npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.4',
  openssl: '1.0.2n',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.50',
  zlib: '1.2.11' }
-----------------------------------------
tns --version
4.0.2
----------------------------------------
"nativescript-plugin-firebase": "5.3.1"
```

**Comment by EddyVerbruggen** [comment]
Did you Google the error? It doesn't ring a bell here.

**Comment by rigoparis** [comment]
Hey Eddy!

Yeah, I've searched for that error but just nonsense comes up.

I've deducted that it's not the plugin but something about how my app initializes. Since I started a brand new proyect with all the plugins im using (only initializing `nativescript-plugin-firebase`) and the push notifications work fine... 

I did find a small bug on the clean build (I only tested this with just 1 phone and with only `nativescript-plugin-firebase` installed): When the app is minimized and a push notification opens it, the app appears to freeze but it doesn't, you can click buttons and you can see the animation of the button being clicked but nothing happens. If the app is closed everything works fine.

I'll go ahead and continue debugging to see whats up with that error and I'll post here anything I find for future references

Thanks Ed!

**Comment by erkanarslan** [comment]
@rigoparis Did you find a solution? I am facing the same problem.

**Comment by rigoparis** [comment]
@erkanarslan Negative, after much testing and trying different things I came to the conclusion that the configuration and Android API I was using in that project is simply not compatible with the plug-in.

I went ahead and changed the plug-in for Nativescript's own `nativescript-push-notifications` and everything works fine.

Hope that helps man! If anything, I'm open for questions.

**Comment by saibbyweb** [comment]
### THIS WORKED FOR ME

I was having the same problem. On Android Pie
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onViewAttachedToWindow failed

Error: Cannot assign primitive value to array of objects.
File: "file:///data/data/org.nativescript.nsvuepilot/files/app/vendor.js, line: 43006, column: 26

```
On a physical device running Marshmallow:

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException
Calling js method run failed
Error: java.lang.NoSuchFieldError: no "I" field "BYTES" in class "Ljava/lang/Long;" or its superclasses
com.tns.Runtime.callJSMethodNative(Native Method)

```

### THE PROBLEM WAS WITH THE CALLBACK

I was directly feeding the **message** received to console, removing or stringfying the message solved the issue for me
```
  onMessageReceivedCallback: (message) => {
    console.log(message)
  }
```
to

```
  onMessageReceivedCallback: (message) => {
    console.log(message.toString())
  }
```

**Comment by juanrdlo** [comment]
return '[object Object]' not solution :(
