### ISSUE TITLE
getting this error every time on resume activity

### ISSUE THREAD

**Issue by JaganJonnala** [EddyVerbruggen/nativescript-plugin-firebase#724]
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onTransitionEnd failed

TypeError: Cannot read property 'delete' of undefined
File: "file:///data/data/org.nativescript.qwipo/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js, line: 552, column: 11

StackTrace: 
	Frame: function:'transitionOrAnimationCompleted', file:'file:///data/data/org.nativescript.qwipo/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 552, column: 12
	Frame: function:'TransitionListenerImpl.onTransitionEnd', file:'file:///data/data/org.nativescript.qwipo/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 219, column: 17

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Ru

**Comment by EddyVerbruggen** [comment]
That stacktrace doesn't show anything related to this plugin. You'll need to dig deeper and narrow it down I'm afraid.
