### ISSUE TITLE
Google Service conflits on using nativescript-admob with this plugin

### ISSUE THREAD

**Issue by calebeaires** [EddyVerbruggen/nativescript-plugin-firebase#85]
Both plugin don`t work together and give error on build 

```Exception in thread "main" java.lang.IllegalArgumentException: Class com.google.android.gms.internal.zzqi conflict: /Users/calebeaires/Downloads/tresdobras/platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-base/9.2.0/jars/classes.jar and /Users/calebeaires/Downloads/tresdobras/platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-analytics/7.5.0/jars/classes.jar
	at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:39)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED```

**Comment by calebeaires** [comment]
Duplicated: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/55
