### ISSUE TITLE
demo-ng project 

### ISSUE THREAD

**Issue by abhayastudios** [EddyVerbruggen/nativescript-plugin-firebase#864]
Anyone else getting an error while running the `demo-ng` project (after replacing the plugin dependency to `^6.5.0`) ? The `demo` project seems to be working fine.

```
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.firebasedemo.firestore/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: Invalid provider for undefined. useClass cannot be undefined.
System.err:            Usually it happens when:
System.err:            1. There's a circular dependency (might be caused by using index.ts (barrel) files).
System.err:            2. Class was used before it was declared. Use forwardRef in this case.
System.err: File: "file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js, line: 11042, column: 16
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1298, column: 33
System.err: 	Frame: function:'syntaxError', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 287, column: 21
System.err: 	Frame: function:'CompileMetadataResolver._validateProvider', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10924, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10884, column: 31
System.err: 	Frame: function:'CompileMetadataResolver._getProvidersMetadata', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10876, column: 23
System.err: 	Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10595, column: 63
System.err: 	Frame: function:'CompileMetadataResolver.getNgModuleSummary', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10425, column: 39
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10512, column: 59
System.err: 	Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10490, column: 53
System.err: 	Frame: function:'JitCompiler._loadModules', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 22602, column: 55
System.err: 	Frame: function:'JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 22583, column: 40
System.err: 	Frame: function:'JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 22543, column: 41
System.err: 	Frame: function:'CompilerImpl.compileModuleAsync', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js', line: 192, column: 35
System.err: 	Frame: function:'PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4341, column: 29
System.err: 	Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/nativescript-angular/platform-common.js', line: 75, column: 66
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/nativescript-angular/platform-common.js', line: 128, column: 19
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err: 	Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 870, column: 17
System.err: 	Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 803, column: 28
System.err: 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 677, column: 14
System.err: 	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
System.err: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: Error: Invalid provider for undefined. useClass cannot be undefined.
System.err:            Usually it happens when:
System.err:            1. There's a circular dependency (might be caused by using index.ts (barrel) files).
System.err:            2. Class was used before it was declared. Use forwardRef in this case.
System.err: File: "file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js, line: 11042, column: 16
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1298, column: 33
System.err: 	Frame: function:'syntaxError', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 287, column: 21
System.err: 	Frame: function:'CompileMetadataResolver._validateProvider', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10924, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10884, column: 31
System.err: 	Frame: function:'CompileMetadataResolver._getProvidersMetadata', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10876, column: 23
System.err: 	Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10595, column: 63
System.err: 	Frame: function:'CompileMetadataResolver.getNgModuleSummary', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10425, column: 39
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10512, column: 59
System.err: 	Frame: function:'CompileMetadataResolver.getNgModuleMetadata', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 10490, column: 53
System.err: 	Frame: function:'JitCompiler._loadModules', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 22602, column: 55
System.err: 	Frame: function:'JitCompiler._compileModuleAndComponents', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 22583, column: 40
System.err: 	Frame: function:'JitCompiler.compileModuleAsync', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js', line: 22543, column: 41
System.err: 	Frame: function:'CompilerImpl.compileModuleAsync', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js', line: 192, column: 35
System.err: 	Frame: function:'PlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4341, column: 29
System.err: 	Frame: function:'_bootstrapper', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/nativescript-angular/platform-common.js', line: 75, column: 66
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/nativescript-angular/platform-common.js', line: 128, column: 19
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
System.err: 	Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 870, column: 17
System.err: 	Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 803, column: 28
System.err: 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 677, column: 14
System.err: 	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.firebasedemo.firestore/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
System.err: 	at android.app.Activity.performCreate(Activity.java:7183)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
System.err: 	... 9 more
```

**Comment by abhayastudios** [comment]
PR #866 fixes this
