### ISSUE TITLE
[MLKIT barcode in android & Nativescript-Vue 2.0.0] open again seem error `TypeError: Cannot read property 'getHolder' of null`

### ISSUE THREAD

**Issue by hoatructhanhlam** [EddyVerbruggen/nativescript-plugin-firebase#920]
First open, it fine. But when I back and try open again I got log error:
I using MLKIT with Nativescript-Vue latest on android
```
System.err: com.tns.NativeScriptException:
System.err: Calling js method run failed
System.err:
System.err: TypeError: Cannot read property 'getHolder' of null
System.err: File: "file:///data/data/vn.zeko.app/files/app/vendor.js, line: 24351, column: 44
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'', file:'file:///data/data/vn.zeko.app/files/app/vendor.js', line: 24351, column: 45
System.err: 	Frame: function:'invoke', file:'file:///data/data/vn.zeko.app/files/app/vendor.js', line: 51965, column: 21
System.err: 	Frame: function:'run', file:'file:///data/data/vn.zeko.app/files/app/vendor.js', line: 51971, column: 7
System.err:
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err: 	at android.os.Handler.handleCallback(Handler.java:754)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:165)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6375)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
```

**Comment by evertonrobertoauler** [comment]
Same problem here, after upgrading from 6.7.0 to the latest versions I started to get this error too only on Android, the first time the component loads it works fine, but de second time it crashes. I'm using Nativescript w/ Angular

**Comment by EddyVerbruggen** [comment]
Please share a repo I can easily clone and reproduce this issue.

**Comment by hoatructhanhlam** [comment]
Sorry for my delay, this is respo contains the content above
[https://gitlab.com/phamvandung/mlkit-nativescript-vue](url)

**Comment by victordcp** [comment]
Same problem here, the exact same case from @evertonrobertoauler.
