### ISSUE TITLE
Error initializing firebase

### ISSUE THREAD

**Issue by PedroAnibarro1** [EddyVerbruggen/nativescript-plugin-firebase#95]
Hi,

The plugin throws this error randomly. 

     firebase.init error: Error: java.lang.NullPointerException: Argument 'applicationContext' cannot be null

Sometimes it works, sometimes it doesn't. Any idea?

Update:

This is what is being shown on screen

![screenshot_2016-08-03-15-57-49](https://cloud.githubusercontent.com/assets/8890152/17380102/5ab107d6-5993-11e6-9f60-607a44e61ee5.png)

I noticed that if I remove `firebase.addChildEventListener(this.onChildEvent, "/menu");` the app works (obviously without that feature, but at least it opens).

**Comment by PedroAnibarro1** [comment]
This is the whole error message on phone:

com.tns.NativeScriptException: 
Calling js method onCancelled failed

Error: java.lang.AbstractMethodError: abstract method "void com.google.firebase.database.ChildEventListener.onCancelled(com.google.firebase.database.DatabaseError)"
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
    com.tns.Runtime.callJSMethod(Runtime.java:712)
    com.tns.Runtime.callJSMethod(Runtime.java:693)
    com.tns.Runtime.callJSMethod(Runtime.java:683)
    com.tns.gen.com.google.firebase.database.ChildEventListener.onCancelled(ChildEventListener.java:38)
    com.google.android.gms.internal.zzahh.zza(Unknown Source)
    com.google.android.gms.internal.zzajf.zzctc(Unknown Source)
    com.google.android.gms.internal.zzajk$1.run(Unknown Source)
    android.os.Handler.handleCallback(Handler.java:815)
    android.os.Handler.dispatchMessage(Handler.java:104)
    android.os.Looper.loop(Looper.java:194)
    android.app.ActivityThread.main(ActivityThread.java:5643)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
File: "<unknown>, line: 0, column: -1

StackTrace: 

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
at com.tns.Runtime.callJSMethod(Runtime.java:712)
at com.tns.Runtime.callJSMethod(Runtime.java:693)
at com.tns.Runtime.callJSMethod(Runtime.java:683)
at com.tns.gen.com.google.firebase.database.ChildEventListener.onCancelled(ChildEventListener.java:38)
at com.google.android.gms.internal.zzahh.zza(Unknown Source)
at com.google.android.gms.internal.zzajf.zzctc(Unknown Source)
at com.google.android.gms.internal.zzajk$1.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5643)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.AbstractMethodError: abstract method "void com.google.firebase.database.ChildEventListener.onCancelled(com.google.firebase.database.DatabaseError)"
... 18 more

**Comment by PedroAnibarro1** [comment]
I think that this error is this one #48

**Comment by PedroAnibarro1** [comment]
I think my problem was the read rules of my firebase database.... My bad 😅

My problem was that I changed the authentication system and forgot to change my rules. Hope this helps someone.

**Comment by codeback** [comment]
Hi @colinskow, 

I'm having the same issue in the"query" method when singleEvent property is false. If the user does not have permissions (read rules), the app crashes.

Any idea? thanks.

**Comment by sivsushruth** [comment]
Hey, this issue still seems to persist, can we handle a callback ?

**Comment by colinskow** [comment]
If the app is crashing on an error it means the NativeScript binding is missing a handler for it.
